### ISSUE TITLE
multivariate L1 distance after CEM

### ISSUE THREAD

**Issue by yceny** [kosukeimai/MatchIt#100]
Is there any way to get multivariate L1 distance after run cem using matchit?

**Comment by ngreifer** [comment]
Please see here: https://stackoverflow.com/questions/70892121/obtain-the-l1-imbalance-measure-for-cem-methodology-in-matchit

**Comment by yceny** [comment]
> 

Thanks. This is very helpful. Is there a way to calculate imbalance (L1 distance) measure for each variable before and after the matching? The link calculates overall L1 measure.

**Comment by ngreifer** [comment]
Please see here: https://stackoverflow.com/q/60725005/6348551
