### ISSUE TITLE
optmatch missing from CRAN

### ISSUE THREAD

**Issue by vektor8891lilly** [kosukeimai/MatchIt#101]
Matchit requires "optmatch" when performing full matching which has been recently removed from CRAN.

https://cran.r-project.org/web/packages/optmatch/index.html
![image](https://user-images.githubusercontent.com/86112115/156833178-2c1c57a5-68b3-4c67-9a5c-5e805dd42b64.png)

**Comment by ngreifer** [comment]
We are aware, but there is nothing we can do until `optmatch` has returned. We are in contact with the `optmatch` developers, who claim it should be returned soon. If you want to perform optimal or full matching, you can install an archived version of `optmatch` from CRAN.
