### ISSUE TITLE
ratio = 0.5 is not supported

### ISSUE THREAD

**Issue by Shicheng-Guo** [kosukeimai/MatchIt#108]
Hi Kosuke, 

I am wondering why ratio =0.5 is not supported?  1 control match two cases should be okay, correct? 

Or we need to reverse the labelling? 

Thanks

Shicheng

**Comment by ngreifer** [comment]
When `estimand = "ATT"` (the default), each case receives a match, and `ratio` controls how many matches each case gets. If you want instead for each control unit to get a match and for `ratio` to control how many matches each control gets, simply set `estimand = "ATC"`. No need to change the labeling.
