### ISSUE TITLE
Summaries of match objects have different columns and column order

### ISSUE THREAD

**Issue by GreenGrape80** [kosukeimai/MatchIt#11]
The summary output differs between full matching and nearest-neighbor matching.  For full matching, the standardized difference is in the 3rd column of the summary output and for nearest-neighbor, it’s in the 4th column.  

Let's say that this is my code (took out excessive variables for clarity).

model1<-matchit(formula= y ~ x1 + x2, exact=c("x3", "x4"), mahvars=c("x5", "x6"), data=NS, method="nearest", distance = "logit",  caliper=0.25, replace=T, calclosest=T, ratio=3, verbose=T)
df.addl=with(data.frame(x7, x8), data=NS)
m.out=summary(model1, standardize=T, addlvariables=df.addl)
names(m.out$sum.matched)
[1] "Means Treated"   "Means Control"   "Std. Mean Diff." "eCDF Med"        "eCDF Mean"      
[6] "eCDF Max"       
model2<-matchit(formula= y ~ x1 + x2 +x3 + x4 + x5, data=NS, method="full", verbose=T)
df.addl=with(data.frame(x6, x7, x8), data=NS)
m.out2=summary(model2, standardize=T, addlvariables=df.addl)
names(m.out2$sum.matched)
[1] "Means Treated"   "Means Control"   "SD Control"      "Std. Mean Diff." "eCDF Med"       
[6] "eCDF Mean"       "eCDF Max"       

This problem was replicated many times by my students in the spring term, as many students produced Love plots for their projects or replications of National Supported Work study that looked fishy because they were not plotting the standardized differences.

**Comment by GreenGrape80** [comment]
Here's the version with the lalonde data.  Columns are different here as well, but the column names are slightly different than above, for some reason.  

> model1=matchit(treat ~ re75, method="nearest", data=lalonde)
> model2=matchit(treat ~ re75, method="full", data=lalonde)
Warning message:
In optmatch::fullmatch(d, ...) :
  Without 'data' argument the order of the match is not guaranteed
    to be the same as your original data.
> model1.summary=summary(model1)
> model2.summary=summary(model2)
> names(model1.summary$sum.all)
[1] "Means Treated" "Means Control" "SD Control"    "Mean Diff"     "eQQ Med"      
[6] "eQQ Mean"      "eQQ Max"      
> names(model2.summary$sum.all)
[1] "Means Treated" "Means Control" "Mean Diff"     "eQQ Med"       "eQQ Mean"     
[6] "eQQ Max"

**Comment by alexWhitworth** [comment]
@GreenGrape80 Thank you for bringing up this issue. I'm a little confused however. Are you suggesting that this causes a problem with some downstream work or simply that the column names are different in the summary object? That is, it's not clear to me what your proposed solution or ideal end-state is. Could you please elaborate? Thanks!

@kosukeimai This is because we have different summary methods for the different sub-classes (eg. `summary.matchit.full` and `summary.matchit` or the associated `print` methods). This adds to [technical debt](https://en.wikipedia.org/wiki/Technical_debt) in the code base. It's probably worthwhile to resolve for that alone. 

PS - I don't have time currently, since I need to debug [this](https://github.com/alexWhitworth/synthACS/issues/1) when I get back from my upcoming vacation.

**Comment by GreenGrape80** [comment]
It causes problems with downstream work, especially the change of column order.  I suspect that the change of which columns are present and the labels could be a problem for others.  There’s no way to automate making Love plots in a way that will be the same for each type of matching.  I like to use a function for myself, and I give that code to my students when I teach causal inference.  

No hurry --- I first noticed the problem a few years ago, but until recently I just had a vague awareness of needing to check that I was using the correct column because sometimes it was thd 3rd column and sometimes the 4th column.

**Comment by alexWhitworth** [comment]
@GreenGrape80  Can you please update your reproducible example to illustrate the problem that it causes then? I'm unfamiliar with "love plots" or the function you wish to use for your students.

**Comment by GreenGrape80** [comment]
That's actually not possible because as you can see above, the names of the columns vary in my two examples.  In my first example, the standardized difference is in a column called "Std. Mean Diff." and in the second example, the column is called  "Mean Diff".

**Comment by ngreifer** [comment]
This has been fixed. The column names are now the same across matching methods, except for subclassification, which functions a little differently. The column names will differ depending on whether `standardize` is set to `FALSE` or `TRUE`, but across matching methods will be the same.
