### ISSUE TITLE
Possible Infinite Loop when Exact Matching for Method = 'Nearest'

### ISSUE THREAD

**Issue by bking124** [kosukeimai/MatchIt#111]
I am trying to run a matching analysis with some education data.  My plan is to exact match on several demographic variables and then do nearest neighbor matching on a numeric score variable.  So ana example call would be 

```
matched <- matchit(group ~ ethnicity + gender + score, method = "nearest",
               exact  = ~ ethnicity + gender, data = df)
```
Now, I ran this on my dataset and the code just wouldn't complete, even though the dataset was very small and I am not choosing a complicated method.  After doing some digging, I believe this has something to do with the behavior of the exactify function and `sep` variable, in particular this while loop https://github.com/kosukeimai/MatchIt/blob/0e4d3b2f922440a912730a4b478981ee09fb3947/R/aux_functions.R#L734-L736

When called from `matchit2nearest`, `sep=", "` is passed in.  As it turns out, my ethnicity variable also had commas, so the while loop was entered.  But there is no way that the while loop can be exited.  Once I realized this, I recoded my ethnnicity variable so that it had more standard names, and everything worked well after that.  Nevertheless, I thought the issue was worth raising.  I'm not sure what the `sep` variable and this while loop is supposed to do, but as it stands it definitely could lead others into a potential problem.

**Comment by ngreifer** [comment]
Thank you so much for letting me know! That does look like a poorly programmed loop. I'll work on a fix for that now.
