### ISSUE TITLE
Errors from using random forest 

### ISSUE THREAD

**Issue by recordyao** [kosukeimai/MatchIt#115]
I'm trying to use random forest as PSM. For the same dataset, while distance = "glm" works fine, distance = "randomforest" generates some errors. It says

 "Error in na.fail.default(list(sep_citing = c(NA_integer_, NA_integer_,  : 
  missing values in object"

I'm sure there is no missing values, nor any NAs in my dataset. 
Any suggestions?

**Comment by recordyao** [comment]
In both cases of glm and randomforest I'm using method = "nearest"

**Comment by ngreifer** [comment]
It would be great if you could send me your dataset and the `MatchIt` code you used. If you can't send me your dataset, another dataset (possible fake) where the problem arises as well would work. I am able to recreate this error only when there actually are missing values in the data, so there may be missing values you are not aware of. Again, if you send me your data and code I can properly diagnose this. Thanks.
