### ISSUE TITLE
Improve error output of `matchit()`

### ISSUE THREAD

**Issue by buhtz** [kosukeimai/MatchIt#117]
I know why this error occur

`Error: Missing values are not allowed in the covariates.`

when I do this 
```
m.out0 <- matchit(
    group ~ a + b + c,
    data = df,
    method = NULL,
    distance = "glm"  # "generalized linear model"
)
```

But the error output should tell me which columns have missing values. This would be nice.

**Comment by ngreifer** [comment]
This is a great suggestion, thanks!

**Comment by ngreifer** [comment]
Actually I've already fixed this in the development version, which you can install using `remotes::install_github("ngreifer/MatchIt")`.
