### ISSUE TITLE
How larger is the value of caliper by default when the method was set with “nearest” . 

### ISSUE THREAD

**Issue by skywalker21th** [kosukeimai/MatchIt#118]
If we analysis the data by the code as the example in the document:

1:1 NN PS matching w/o replacement
m.out1 <- matchit(treat ~ age + educ + race + married +
nodegree + re74 + re75, data = lalonde,
method = "nearest", distance = "glm")

In the example, we can find the value of caliper was not defined.
So how larger is the value of caliper in the PS matching code when the method was set with “nearest” (method_nearest, Nearest Neighbor Matching).
That is, how larger is the value of caliper by default in the PS matching code when the method was set with “nearest” .

Or the caliper was not considered as a Parameter at the situation.
If we would not define a caliper, there is none caliper.
What's the truth？

Thanks!

**Comment by ngreifer** [comment]
Please see the documentation for the `caliper` argument at `?matchit`.

**Comment by skywalker21th** [comment]
> Please see the documentation for the `caliper` argument at `?matchit`.

Thank you very much!
We have read the document of Package ‘MatchIt’ (version 4.4.0) on page 18.
"  caliper:   for methods that allow it, the width(s) of the caliper(s) to use in matching. Should be a numeric vector with each value named according to the variable to which the caliper applies. To apply to the distance measure, the value should be unnamed. See the individual methods pages for information on whether and how this argument is used. The default is NULL for no caliper."

So  we think that the default is NULL for no caliper in our situation as follow: 

" 1:1 NN PS matching w/o replacement
m.out1 <- matchit(treat ~ age + educ + race + married +
nodegree + re74 + re75, data = lalonde,
method = "nearest", distance = "glm") 
"

Did I ignore any important information?

Many thanks

**Comment by ngreifer** [comment]
That's correct. If unspecified, there is no caliper. See my justification in #110 if you're interested in why this is the default.
