### ISSUE TITLE
"antiexact" not working as expected

### ISSUE THREAD

**Issue by gli-1** [kosukeimai/MatchIt#119]
Hello, 

I was trying to use "antiexact" in matching, but some matched pairs still have the same value of the variable specified in "antiexact". Below is an example to illustrate the issue - I exact match pr=1 and pr=0 on ct, with antiexact match on pt. I expect all matched pairs to have different values of pt, but in the output data (testdat), subclass 1 and 2 have the same values of pt within each matched pairs. 

I wonder why "antiexact" did not work as I expected here. Any suggestions would be appreciated! 

Code:
library(optmatch)
library(MatchIt)
data(nuclearplants)
set.seed(1)
match_antiexact <- matchit(pr~ct, data=nuclearplants, exact= ~ct, antiexact = ~pt, method = "nearest") 
testdat <- match.data(match_antiexact, drop.unmatched=TRUE)

**Comment by ngreifer** [comment]
That's a bug! Thank you so much for letting us know. I'll do my best to fix it and get back to you when it has been solved.
