### ISSUE TITLE
Why is `ratio=2` different from two 1:1 iterations

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [kosukeimai/MatchIt#120]
This is more a question then a bug report. I have a full minimal working example describing my problem at StackExchange's CrossValidated: https://stats.stackexchange.com/q/584180/126967

Usually I did `k:1` matches via iterations of `1:1` matches where I simply removed the matched controls from the original dataset between each iteration.

Today I found out about the `ratio` argument and did some tests. The resulting rowname are different between making two `1:1` iterations compared to `ratio=2`.

I would like to understand why.

**Comment by ngreifer** [comment]
Hi, great question! I posted my answer there. Essentially, it's because the way you coded it, you estimate a new propensity score only among the subset of unmatched when doing the second round of 1:1 matching. If you use a single set of propensity scores for everyone by estimating them before doing the matching, or if you use the `discard` option to drop previously matched cases instead of removing cases from the dataset, you will get the same matched set.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I don't get all details but I think I understand the basics and can sleep better now. Thanks a lot.

I think my problem is that the PS is still a "magic number" for me. I don't know how this is calculated and I also don't see a PS in the resulting data. I only see `distance`, `weight` and `subclass` added as extra informations.

**Comment by ngreifer** [comment]
`distance` is the propensity score. The reason we call it `distance` is that it doesn't have to be a propensity score; it can be some other number used for matching or a transformation of the propensity score. See [here](https://stats.stackexchange.com/q/407764/116195) for an explanation of this.

You don't need to understand the propensity score as anything other than a balancing score, i.e., a variable that when matched on yields balance. It is magic in a way. It is estimated as the predicted probability of receiving treatment resulting from a model for the treatment given the covariates. By default (with `distance = "glm"`), they are the predicted values resulting from a logistic regression model of the treatment on the covariates.

Running a logistic regression model in a subset of the data will give you different propensity scores from running the model in the full dataset. When doing 2:1 matching, the model is run in the full dataset; in the second iteration of 1:1 matching as you implemented it, the model is only run in a subset of the data, which means each remaining unit gets a new propensity score different from their original propensity score. Matching on the new propensity score yields different results, which is the cause of the discrepancy.
