### ISSUE TITLE
Interpretation balance statistics

### ISSUE THREAD

**Issue by ncz11** [kosukeimai/MatchIt#122]
Hello, 

I have a rookie question:
looking at the example, in the Summary of Balance the values for Matched Data the Std. Mean Diff. are mostly zero (exception being re74 and re75). Shouldn't this mean that the matching was achieved?

**Comment by ngreifer** [comment]
I wouldn't say that matching has been achieved, but that *balance* has been achieved on the variables with low SMDs. SMDs aren't the only measure of balance, though, so other statistics are important to look at to determine whether the matched samples are well balanced.

For more information on how to assess balance and what the balance output means, see the `MatchIt` [vignette](https://kosukeimai.github.io/MatchIt/articles/assessing-balance.html) on assessing balance or the `cobalt` [vignette](https://ngreifer.github.io/cobalt/articles/cobalt.html).
