### ISSUE TITLE
What is the meaning of a negative Standardized mean difference (SMD)?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [kosukeimai/MatchIt#124]
I also have opened a [CrossValidated question](https://stats.stackexchange.com/q/585545/126967) about that.

The MatchIt docu shows negative SMD values in the `summary()`.

But [Linden (2013)](https://doi.org/10.1111/jep.12072) doesn't. Linden explains (regarding to the literature) that someone can set an own cutoff value somewhere between `0.1` or `0.25`.

But how to interpret a negative SMD like `-0.023`. Is it super balanced? ;)

My assumption is that I tottaly misunderstood something.

**Comment by ngreifer** [comment]
Question answered. SMDs aren't presented in absolute value in `MatchIt`. Negative SMDs imply the control group has a larger mean than the treated group. Cutoffs refer to absolute SMDs.
