### ISSUE TITLE
nn table disappeared? 

### ISSUE THREAD

**Issue by ilovemane** [kosukeimai/MatchIt#125]
Hi,

I realised the mathcit_object$nn has disappeared in the new version of matchit. Is that true? Is there a new way to get the information used to be in the nn table?

thanks,

Mike

**Comment by ngreifer** [comment]
Yes, this was changed in `MatchIt` version 4.3.2. You need to extract it from the `summary()` output. You can also run the following:
```
with(m.out, MatchIt:::nn(treat, weights, discarded, s.weights))
```
assuming `m.out` is your `matchit` object. This won't work in other packages if they are to be published on CRAN, of course.
