### ISSUE TITLE
Template matching using gurobi solver with weighted survey data, matching never converge to optimal sollution

### ISSUE THREAD

**Issue by label42** [kosukeimai/MatchIt#127]
Hi,

We are facing an issue with template matching on weighted survey data using Gurobi solver. It seems like the solver is trapped in an endless loop even if it as found the optimal solution. We have to set up a timer to stop it. Timer at 30s, 1 min, 15 min or 1 hour gives the exact same results (same number of matched individuals, same covariates equilibrium), with a warning that "solution may not be optimal". The solution Gurobi find seems converge after a few sec, and don't change even if we wait for an hour. When we perfom matching on non weitghted data, same covariates, the solver find the optimal solution in a few seconds and stop by himself.

I suspect a bug due to weighting. Do you have any information about that ? 

Thank you for your time.

**Comment by ngreifer** [comment]
Unfortunately, this is an inherent problem with Gurobi, not with `MatchIt`, and there isn't anything I can do about it. It frustrates me, too, and there are many other scenarios where this kind of thing happens. I think this is just a limitation of the current technology. My guess is that there are certain kinds of problems for which deciding on convergence requires searching through the full solution space, even once an adequate solution has been found. You can perhaps contact Gurobi for more information about this, but I would guess they won't have much to say about it except to fiddle with the control parameters.
