### ISSUE TITLE
duplicate rows in the lalonde data 

### ISSUE THREAD

**Issue by waynelapierre** [kosukeimai/MatchIt#130]
```
require(MatchIt)
require(data.table)
data(lalonde)
setDT(lalonde)
nrow(lalonde) > uniqueN(lalonde)
```
Since your examples are based on this dataset, I am not sure if this could be an issue. Anyway, it makes sense to remove the duplicate rows.

**Comment by ngreifer** [comment]
Those duplicates represent real people who happen to have equal covariate values. Nothing unusual or problematic about that. There is nothing about the data or methods that would require each row to be distinct.
