### ISSUE TITLE
Provide alt= accessibility attributes for vignettes

### ISSUE THREAD

**Issue by MichaelChirico** [kosukeimai/MatchIt#134]
`knitr` provides the `fig.alt` chunk option to improve vignette accessibility; there are several figures in `MatchIt` vignettes that have un-annotated figures, making it more difficult for screen reader users to consume the content:

```
MatchIt.html: lines 709, 714, 776
assessing-balance.html: lines 814, 860, 874, 888, 1043, 1056, 1177, 1191, 1206, 1209, 1213
```

These .html line references are w.r.t. the .html files bundled on CRAN version 4.5.0.

**Comment by ngreifer** [comment]
Thank you for this suggestion! I'll work on this shortly.

**Comment by MichaelChirico** [comment]
LGTM! thanks for this.

FWIW I personally find long fig.alt entries as a good reason to switch to the new comment-based chunk argument style (see https://yihui.org/knitr/options/). up to preference though!
