### ISSUE TITLE
Match cases on string distance

### ISSUE THREAD

**Issue by giuliogcantone** [kosukeimai/MatchIt#135]
I have a dataset of records such that

$y$ is a number.
$x$ is logical (treatment).
$z$ is a string of elements, e.g.: $z: {a,b,c,...}$. Let's assume these elements are characters.

I could expand $z$ into a $Z$ set of columns with logical values: $Z: {z_a, z_b, z_c,...}$. Then, each record raw has a certain distance (Hamming, Cosine, Jaccard, etc) from each other.

To my knowledge, string distances are not implemented in MatchIt. Is there a way to implement them?
Also, I ask myself if this expansion is really necessary, i.e. maybe there are other distances that take a vector of characters as input.

**Comment by ngreifer** [comment]
They are not explicitly implemented in `MatchIt`, but you can compute any arbitrary distance outside of `MatchIt` and supply it to the `distance` argument in `matchit()`. I have not seen distances other than the ones currently available be used in the matching literature, so they are not in `MatchIt`, but there will always be specialized cases where a specific distance measure makes more sense for a given application. The ability to supply an externally computed distance means that `MatchIt` doesn't have to implement all possible distance measures to provide users access to the distance measure of their choice.
