### ISSUE TITLE
Match 1-to-many cases on distances on sum of statistics.

### ISSUE THREAD

**Issue by giuliogcantone** [kosukeimai/MatchIt#136]
I have a dataset of records such that

$y$ is a number.
$x$ is logical (treatment).
$k$ is a number.
$Z$ are other numeric columns.

I want to match cases such that for each $x=1$ there is a group of $x=0$ such that $k_{x=1} \sim \sum k_{x=0}$, plus the differences in $Z$ are minimized too. It is not necessary for (records in the) groups to be exclusive to a $x=1$, but it would be great if the algorithm gives priority to minimizing the error in $k_{x=1} \sim \sum k_{x=0}$.

**Comment by ngreifer** [comment]
I have never encountered an algorithm that can do this, so there is certainly not one available in `MatchIt` for this. A way to trick `matchit()` into doing something like this would be the following:

Select a fixed matching ratio $m$:1, e.g., 3:1. Create a new variable, `k_new`, which is `k` for the treated and `k*m` for the control. Do a nearest neighbor, optimal, or cardinality match with `ratio = m`. If the mean of `k_new` in the matched treated group is equal to the mean of `k_new` in the control group, then the sum of `k` in the treated group will be equal to the sum of `k` in the control group. This would not produce subsets with equal sums, but it would create overall groups with equal sums.
