### ISSUE TITLE
Matching on character variables broken again in 4.5.0

### ISSUE THREAD

**Issue by isfraser** [kosukeimai/MatchIt#138]
In the 4.3.1 update you note 

"Fixed a bug introduced in 4.3.0 where the inclusion of character variables would cause the error "Non-finite values are not allowed in the covariates."

This issue seems to have recurred in 4.5.0 (I apologise, I can't locate it in the issues tracker, or I'd just reopen). Reprex:
![image](https://user-images.githubusercontent.com/43848790/205064722-87615386-0b8c-4d42-912f-b6fa57680e1e.png)

**Comment by isfraser** [comment]
Addendum - this code (and the code that originally broke in my actual project) both run fine in 4.4.0

**Comment by ngreifer** [comment]
Thank you so much for letting me know! I'll fix this right away and have an updated version soon. So sorry about this.

**Comment by ngreifer** [comment]
Okay, I made the fix and it is available on my version of the package at https://github.com/ngreifer/MatchIt, which you can install using

```
remotes::install_github("ngreifer/MatchIt")
```

I'm working on a major update, so this change probably won't make it to CRAN for a while.
