### ISSUE TITLE
Use of caliper with optimal pair matching

### ISSUE THREAD

**Issue by davemerola** [kosukeimai/MatchIt#139]
Is there a way to use a caliper with the optimal pair matching method? The documentation states that the "caliper" argument is ignored when method is set to "optimal" but I was wondering if there is another way to implement this. Thanks!

**Comment by ngreifer** [comment]
Unfortunately, this is a problem not with `MatchIt`, but with `optmatch`. You can ask the `optmatch` maintainers why calipers cannot be used with optimal pair matching. My guess is that either the optimization problem is not well defined in the presence of a caliper, or there is a bug in the package. You actually can use a caliper with optimal pair matching, but if it yields a situation where some treated units are unmatched, the whole match fails.

Nearest neighbor matching often yields similar performance to optimal matching, so I recommend just using that instead.

**Comment by davemerola** [comment]
Thank you very much for your prompt reply!
