### ISSUE TITLE
optimal matching failing when not all treatments can be matched

### ISSUE THREAD

**Issue by sophttan** [kosukeimai/MatchIt#144]
I'm using `matchit` for variable ratio (k:1) optimal matching within exact strata. There's exact matching by 3 variables, `var1`, `var2`, and `var3`, and a distance matrix for optimal matching that was manually created based on `var4`. The overall ratio of control:treatment groups is approximately 6:1, though this varies within strata of the variables for exact matching.

```
matchit(treatment ~ var1 + var2 + var3 + var4, 
                 data = d,
                 distance = distance_matrix, 
                 exact = treatment ~ var1 + var2 + var3,
                 ratio = 5, min.controls = 1, max.controls = 6, method="optimal")
```

I'm running into errors when a treatment group does not have any eligible control groups for matching within exactly matched strata. Instead of discarding a single treatment group that cannot be matched, matching fails, and all data in the strata are discarded. Is there a way to avoid this error?

**Comment by ngreifer** [comment]
Sorry about this! One way to do it would be to exclude the unmatchable group from the matching. You can do this by running an initial match with `method = "exact"`, and then supplying to `discard` whether a unit was matched. Here's how this would look:
```r
m1 <- matchit(treatmeant ~ var1 + var2 + var3, data = d, method = "exact")

m2 <- matchit(treatment ~ var1 + var2 + var3 + var4,
              data = d,
              distance = distance+matrix,
              exact = ~var1 + var2 + var3,
              ratio = 5, min.controls = 1, max.controls = 6, method = "optimal",
              discard = m1$weights == 0)
```
Units that failed the initial test of being exactly matched will remain unmatched in this second run. Let me know if this helps.

**Comment by sophttan** [comment]
Thank you for your quick response! Apologies I wasn't entirely clear before - this issue actually happens during optimal matching within exact strata (after exact matching). Here's an example!

There are 4 units (represented by the 4 lines) that I'm matching in this strata (after exact matching). Blue lines represent treatment units and red lines represent control units. I'm then using optimal matching to match on time, represented by the x-axis. The lines with more overlap/more observation time therefore are better matches. Based on this criteria and because I've specified that matching occurs without replacement, one treatment unit remains unmatched and causes matching in the entire strata to fail. Is there a way to exclude this treatment unit to allow for optimal matching?
<img width="325" alt="image" src="https://user-images.githubusercontent.com/46664329/219123889-8d83e34c-42f7-416e-9110-031b88dc9cc1.png">

**Comment by ngreifer** [comment]
Why is it that the first and third units cannot be matched together? Do you have `Inf`s in your distance matrix that forbid this pair?

**Comment by sophttan** [comment]
Yes I have Infs in the distance matrix that prevent matching if there's no time overlap.

**Comment by ngreifer** [comment]
Ah, I see. This is actually a problem with `optmatch`, not with `MatchIt`. `optmatch` causes the entire matching to fail if the problem is not "feasible", i.e., there is no solution that matches all treated units. There isn't really a way around this because there is no way for `optmatch` to know whether a problem is feasible or not without trying to solve it. This is exactly the reason why calipers are not allowed with optimal pair matching. I see this as a bug; clearly the desired behavior is that treated units that cannot be matched are simply dropped like they are in nearest neighbor matching and full matching; but with optimal pair matching, it just doesn't work.

You are welcome to contact the `optmatch` authors about this problem. Sorry I can't be of more help.

**Comment by sophttan** [comment]
No worries - thank you!
