### ISSUE TITLE
factor variable with distance = "euclidean" triggers warning: variable 'y' is absent, its contrast will be ignored

### ISSUE THREAD

**Issue by MatthieuStigler** [kosukeimai/MatchIt#147]
It seems that having a factor variable as treatment variable will ruin smoothly with some distances, but not with `distance = "euclidean"`, and will trigger a warning? Are treatment variables stored as factor supposed to be fine for `matchit`?

> Warning message:
In model.matrix.default(formula, data = mf, contrasts.arg = lapply(Filter(is.factor,  :
  variable 'treat_fac' is absent, its contrast will be ignored

See code below:

``` r
library(MatchIt)
packageVersion("MatchIt")
#> [1] '4.5.1'

data("lalonde")
lalonde$treat_fac <- as.factor(lalonde$treat)

## works
m.out1 <- matchit(treat_fac ~ age + educ, data = lalonde, distance = "glm")
m.out1 <- matchit(treat ~ age + educ, data = lalonde, distance = "euclidean")

## complains?
m.out1_prob <- matchit(treat_fac ~ age + educ, data = lalonde, distance = "euclidean")
#> Warning in model.matrix.default(formula, data = mf, contrasts.arg =
#> lapply(Filter(is.factor, : variable 'treat_fac' is absent, its contrast will be
#> ignored
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ngreifer** [comment]
Thank you for letting me know about this! This is a bug, but you can ignore the warning.
