### ISSUE TITLE
Optimal Matching & Exact argument throwing  incorrect number of dimensions error

### ISSUE THREAD

**Issue by denmiu** [kosukeimai/MatchIt#148]
Hello, 

I am trying to run through the Optimal Pair Matching example show on: [kosukeimai.GitHub.io/MatchIt/reference/method_optimal.html](https://kosukeimai.github.io/MatchIt/reference/method_optimal.html)

I am simply trying to run the first example with the play dataset provided (“lalonde”)  where the “optimal” method is used in conjunction with the “exact= race” argument. 

`#1:1 optimal PS matching with exact matching on race
m.out <- matchit( treat ~ age + educ + race + nodegree + married + re74 + re75, data = lalonde, method = “optimal”, exact ~ race)`

While I can see that the example shown in the link above produces results when I attempt the same script on my end I get the following error message: 

`Error in mo[ex[treat_ == 1] == e, ex[treat_ ==0] == e ] : incorrect number of dimensions`

The package version of MatchIt that  I am using is the most up to date as far as I can tell: ‘4.5.1’ and 
I have been able to successfully run the next example in the reference guide for the optimal matching method using scaled Euclidean distance.  

Any ideas as to what is going on? And how I might get optimal Matching to run in conjunction with an exact argument?

**Comment by ngreifer** [comment]
Hi Denise,

I'm sorry you're having this problem. This is a bit hard to diagnose without having access to the data and the actual code you used to run it. Would you be able to produce those so I can investigate? Thanks.

**Comment by denmiu** [comment]
@ngreifer i am just using data(‘lalonde’) that is provided by the package/library and the above mentioned code. I have not made any modifications to the dataset.

**Comment by ngreifer** [comment]
Oh, sorry for the misunderstanding. Just to be clear, you are saying that running the following line gives you that error:

```
m.out1 <- matchit(treat ~ age + educ + race + nodegree +
                    married + re74 + re75, data = lalonde,
                  method = "optimal", exact = ~race)
```
(Note this is not the exact code in your original post, which has a few typos.) And have you tried refreshing R and re-installing `MatchIt`, i.e., by going to `Session > Restart R` and then running `install.packages("MatchIt")`?

**Comment by denmiu** [comment]
Yes, you are right there is a typo in the above code (a missing close bracket). But I am running the correct code without the typo as below:

`#1:1 optimal PS matching with exact matching on race:
 m.out <- matchit( treat ~ age + educ + race + nodegree + married + re74 + re75,
 data = lalonde, 
method = “optimal”, 
exact ~ race)`

I have both restarted by r session and reinstalled the matchit package into my sessions with no change to the error message.

**Comment by denmiu** [comment]
Apologies, I’m typing the  code example from my device rather than my computer and I inevitably am missing a few important syntax strokes. My code does read `exact = ~ race` and not `exact ~ race` as previously mentioned above.

I ran the additional suggested lines for `method = “optimal”`, `exact= ~race`, & `distance = p` after running the glm() model. Unfortunately,  I do seem to be getting the same error regarding incorrect number of dimensions. If I run the same lines and comment out `exact = ~ race` as shown below:

`p <- glm(treat ~ age + educ + race + nodegree + married + re74 + re75, data = lalonde,
         family = binomial)$fitted `

` m.out <- matchit(treat ~ age + educ + race + nodegree + married + re74 + re75, 
data = lalonde, 
method = "optimal", 
#exact = ~race,
 distance = p) `
 
Then I am able to run the code and and able to print out summary results for m.out. 

Same result for: 
`m.out <- matchit(treat ~ age + educ + race + nodegree + married + re74 + re75, data = lalonde,
                 method = "optimal", exact = ~race, distance = as.matrix(dist(p))) `
And 
`m.out <- matchit(treat ~ p, data = lalonde,
                 method = "optimal", exact = ~race, distance = "euclidean") `

I am only able to successfully run these after I have commented out the exact argument.

**Comment by ngreifer** [comment]
Thank you so much. So it seems like there is some bug with the `exact` argument that I will look into. Sorry I can't give you a solution right now, except to use nearest neighbor matching, which performs about the same in most datasets.

**Comment by ngreifer** [comment]
I believe I have fixed this issue in the most recent version of `MatchIt` on CRAN. Could you take a look?
