### ISSUE TITLE
Cannot use exact matching with "quick" method

### ISSUE THREAD

**Issue by m-marquis** [kosukeimai/MatchIt#149]
I'm encountering a problem when using the new "quick" method and trying to exact match on a subset of covariates. Is this expected behavior? I couldn't find anywhere in the documentation that said the two parameters were incompatible.

Here's a minimal example that should be sufficient to reproduce the problem in both Matchit v4.5.0 and v4.5.1...it seems to work fine when `method` is set to something other than "quick". 
```
STUDY_IND <- c(1,1,1,1,1,1,0,0,0,0,0,0)
GENDER <- c("M", "M", "M", "F", "F", "F", "M", "M", "M", "F", "F", "F")
AGE_YEARS <- c(12, 22, 35, 40, 60, 63, 1, 25, 28, 30, 60, 70)
test_formula <- as.formula('STUDY_IND ~ GENDER + AGE_YEARS')
df <- data.frame(STUDY_IND, GENDER, AGE_YEARS)
df$GENDER <- as.factor(df$GENDER)
matchit(formula=test_formula,
            data=df,
            method='quick',
            distance='glm',
            exact=c('GENDER')
            )
```

The error message I'm getting is:
```
Error in pair[which(ex == e)[!is.na(p[[e]])]] <- paste(as.character(p[[e]][!is.na(p[[e]])]), : NAs are not allowed in subscripted assignments
```

**Comment by ngreifer** [comment]
Hi, thank you so much for looking into this and sorry about the bug. Turns out it was a simple error on my part and has been fixed in the development version, which you can install using `remotes::install_github("ngreifer/MatchIt")`.

**Comment by m-marquis** [comment]
Great, thank you! That solved the first problem but I'm now having another issue in which I get an error reading "`Error : (from quickmatch) 'data' must contain at least two data points`". 

As far as I can tell it seems to be occurring when there is at least one treatment group subject that needs to be discarded because there was no exact match in the control group (you can reproduce the error in my example code above if you change one of the `GENDER` values to a letter other than "M" or "F").

Is there a simple way to avoid this or does `quickmatch` require all subjects to be matchable?

**Comment by ngreifer** [comment]
Thank you again so much for finding this bug. I have fixed it in the development version.

I credited you in the NEWS document for finding these and leading me to fix them.

**Comment by m-marquis** [comment]
Thanks again! I'm so sorry to keep dragging this out but I'm now getting another error that I think might be unrelated to the previous two: when I try to use the "robust_mahalanobis" distance metric I get an error reading `Error in UseMethod("determinant") : no applicable method for "determinant" applied to an object of class "null"`.

You should be able to reproduce this one in the same example snippet above after changing the distance metric argument. This one doesn't seem to be related to either the use of "`method = "quick"` or exact matching, as I get the same thing with `method=nearest` and no exact matching variables (maybe that means I should have opened a new issue for this; if you'd prefer that I do that just let me know).

**Comment by ngreifer** [comment]
Keep the bug reports coming! These are extremely helpful, so thank you. You are making `MatchIt` better and I am so grateful. This one should be fixed now :)

**Comment by m-marquis** [comment]
Well, that's all for the moment...everything is working great for me now. If anything else pops up I'll be in touch. Thanks again for being so incredibly on top of this!
