### ISSUE TITLE
after update to Version 4.5.1 matchit(method = "nearest", exact = c("race", "age") results in reproducible errors

### ISSUE THREAD

**Issue by PStaus** [kosukeimai/MatchIt#151]
Thank you for the great package. It is very usefull in my project.
After the update from 4.5.0 to 4.5.1 my code stopped working. 
When I installed the previous version the code was running again smoothly. 

The error occured in all of these three cases. With two different error messages. I assume it has something todo with the number of exact matched variables. As I said, everything runs perfectly in the old version.
```
library(MatchIt)
m.out <- matchit(treat ~ educ + race +  age, data = lalonde,
                 replace = FALSE,
                 estimand = "ATT",
                 method = "nearest",
                 distance = "glm",
                 exact = c("race", "age"))

m.out2 <- matchit(treat ~ educ + race +  age, data = lalonde,
                 replace = FALSE,
                 estimand = "ATT",
                 method = "nearest",
                 distance = "mahalanobis",
                 exact = c("race", "age"))


m.out3 <- matchit(treat ~ educ + race +  age, data = lalonde,
                  replace = FALSE,
                  estimand = "ATT",
                  method = "nearest",
                  distance = "scaled_euclidean",
                  exact = c("race", "age"))

```
```
#Error 1:
Error in rbind(integer(0), c(NA, 577L, 586L, 342L, 413L, 583L, 530L, NA,  : 
  number of columns of matrices must match (see arg 2)

#Error 2 and 3:
Error in nn_matchC(treat, ord, ratio, discarded, reuse.max, distance,  : 
  the dims contain missing values
```

Thank you in advance
Best wishes

**Comment by jenniferthompson** [comment]
I'm also getting the `rbind` error with a script which previously ran great under version 4.5.0. That script matched exactly on three variables, and does have some low cell counts in some combinations. I suspect I need to adjust my methodological approach regardless of whether that's causing the error, but did wonder if that issue could be related. Just a hypothesis though - I wasn't able to step through the code in sufficient detail to confirm it.

And I also thank you for the great package - it's making a key project so much easier!

**Comment by ngreifer** [comment]
I made an update to `MatchIt`. Would you try installing the new version from CRAN and let me know if the problems have been solved?

**Comment by aakbarie** [comment]
To continue on this issue, when I match using nearest method on multiple matching and replacement = T, I end up with a control match group that is smaller than the treatment group. As an example, summary() shows control = 297 while matched treatment shows 321. Other methods work as before. I have tried both, 4.5.1 and 4.5.2 and the issue still persists
