### ISSUE TITLE
package 'Matchit' is not available for R version 4.2.3

### ISSUE THREAD

**Issue by jimmycloud** [kosukeimai/MatchIt#154]
As title said, I am not able to run "install.packages("Matchit")" successfully.
The R version is 4.2.3 on Windows 10 and all other R packages have been updated.

**Comment by ngreifer** [comment]
That’s because you didn’t capitalize the “I” in MatchIt. R is
case-sensitive.

**Comment by jimmycloud** [comment]
I see. Changing to MatchIt solves the problem. Thank you.
