### ISSUE TITLE
Weights from Coarsened exact matching (CEM) appears to be wrong

### ISSUE THREAD

**Issue by jiweihe1223** [kosukeimai/MatchIt#155]
I examined the weights from match.data() after applying matchit cem. 
The control weights do not sum to 1 and some are even > 1. 

```
    treat   weights subclass
35      0 2.2187500        1
87      0 2.2187500        1
10      1 1.0000000        1
39      0 0.6339286        2
91      0 0.6339286        2
192     0 0.6339286        2
212     0 0.6339286        2
229     0 0.6339286        2
302     0 0.6339286        2
385     0 0.6339286        2
2       1 1.0000000        2
```

**Comment by ngreifer** [comment]
What makes you think the control weights should sum to 1? The methodology for computing weights after CEM is explained [here](https://kosukeimai.github.io/MatchIt/reference/matchit.html#how-matching-weights-are-computed). See also #83.

**Comment by jiweihe1223** [comment]
Thank you! Sorry, I forgot about the previous question.
After getting control weights based on subclass-specific p/(1-p) for ATT
weights, they should be further divided by the average weights in the
control group.
I was confused with the bal.tab() function. For this function, "For k:1
matching for the ATT, control units are weighted proportional to the
inverse of the number of control units in their stratum. "

**Comment by ngreifer** [comment]
That sentence is still true but is not relevant to CEM, only to k:1 matching.

$$w_0 = \frac{p}{1-p} = \frac{n_{1s}/n_s}{n_{0s}/n_s} = \frac{n_{1s}}{n_{0s}}$$
where $n_{1s}$ is the number of treated units in subclass $s$, $n_{0s}$ is the number of control units in subclass $s$, and $n_{s}$ is the total number of units in subclass $s$. In k:1 matching, the number of treated units in each subclass is 1, so $n_{1s} = 1$ for all $s$, so the control weights are equal to $1/n_{0s}$, that is, (proportional to) the inverse of the number of control units in the stratum. So the formula in the `MatchIt` documentation works there too.

**Comment by jiweihe1223** [comment]
Thanks. Intuitively, I still do not understand why for IPTW weights we can use p/(1-p) directly for ATT control weights. But for CEM, we still need to divide by average weights in the control group.

**Comment by ngreifer** [comment]
You don't need to do that. That was a convention in older versions of `MatchIt` that I retained for historical reasons. Simply using the subclass propensity score weights without standardizing them to sum to the control group sample size will yield the same balance statistics and difference in means, and, if the treatment is interacted with all covariates in the outcome model as recommended in the vignette on estimating effects, the covariate-adjusted effect estimate will be the same. So there is no reason to do this. In future versions of `MatchIt`, I may remove this step to make the weights more transparent.

**Comment by jiweihe1223** [comment]
Thanks.
Just want to mention that dividing weights by a constant in each treatment
group does not make any difference for linear regression using lm().
However, for logistic regression and perhaps Cox model, multiply/divide
weights by a constant matters, unless a sandwich estimator is used. But for
treatment effect after matching, we always use a sandwich estimator.
Perhaps it won't be a problem.

**Comment by ngreifer** [comment]
You must use a sandwich estimator for the variance. It is the only valid estimator. If you estimate treatment effects using the instructions in the vignette, no matter which model you use, the estimates and standard errors will not be affected by multiplying the weights in either treatment group by a constant. The estimates and standard errors will be affected if there are covariates in the model and you don't include all treatment-covariate interactions or if you use the wrong standard error.

You're right that Cox models are affected, though. That's one of many good reasons to avoid them or to only use them with matching methods that have a simple formula for the weights (e.g., fixed k:1 matching).

**Comment by jiweihe1223** [comment]
I see. Thanks. In that case, perhaps it is safer to use this step (although
it makes the weights look less intuitive). It seems including treatment by
covariate interaction in the model after matching is not common.

**Comment by jiweihe1223** [comment]
Actually even with covariate adjustment in the outcome model (without
treatment by covariate interactions), dividing the weights by a constant
within each treatment group does not seem to make any difference to the
variance estimator. But I only tried linear model with continuous outcome.
To be consistent with IPTW, perhaps omitting the last step is more
intuitive.
