### ISSUE TITLE
Small typos in documentation

### ISSUE THREAD

**Issue by fBedecarrats** [kosukeimai/MatchIt#156]
Hi there, thank you for this wonderful package and documentation. I just raise this issue to point out a few typos I spotted while reading the documentation: 
In https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html

- A verb is missing in the fragment: "The most common estimand in matching the average treatment effect in the treated (ATT)"
- Apparent involuntary "the this" in: "we recommend them in most cases and use them judiciously in the this guide".
- I'm not sure but I wonder if numbers shouldn't be singular in: "In general, numbers of replications upwards of 999 are recommended"
- A repeated "we" in:  we we call boot_fun

**Comment by ngreifer** [comment]
Thank you so much for these!
