### ISSUE TITLE
contradictory information on propensity score estimate

### ISSUE THREAD

**Issue by peisenha** [kosukeimai/MatchIt#157]
Thank you very much for providing this great toolbox. While exploring the implementation details of propensity score matching under common support restrictions, I came across a puzzling feature that I wanted to flag for you going forward .. or better understand myself. If I set `reestimate = TRUE, discard= "both"` and run propensity score matching on the Lalonde Dataset, then accessing the propensity score through `matchit_obj$model$fitted.values`  returns `NA` for dropped observations. When accessing the same information through a matched dataset then the initial estimate of the propensity score is returned.

See example code and output for details: 

```
  library("MatchIt")
  data("lalonde")
  
  head(lalonde)
  
  matchit_obj <- matchit(treat ~ age + educ + race + married + 
                      nodegree + re74 + re75, data = lalonde,
                    method = "nearest", discard="both", reestimate = TRUE)
  
  # Unit NSW132 is outside the common support and dropped for the re-estimation of 
  # the propensity score model. Thus, the estimated propensity score is NA.
  matchit_obj$model$fitted.values["NSW132"] # returns NA
  
  # However, when looking for the propensity score information in the matched data 
  # frame, then we get the estimate from the first estimation of the propensity
  # score model.
  df_matched_data = match.data(matchit_obj, drop.unmatched = FALSE)
  df_matched_data["NSW132", "distance"] # returns 0.7906385
```

**Comment by ngreifer** [comment]
Hi Philipp, I agree this is strange. Unfortunately there are a few competing desiderata that lead to this unintuitive behavior. I'm not sure how to resolve this, and I think I simply adapted the old way of doing this when I took over `MatchIt`.

Here are the things I have to reconcile:

1.  Every individual gets an initial propensity score
2. Only some individuals get a second propensity score
3. Both propensity scores are used in matching: the first in common support and the second in pairing
4. The output should have a propensity score for every individual
5. It isn't clear whether balance diagnostics should occur on the first or second propensity score

I think one way of justifying the current practice is that the purpose of re-estimating the propensity score is to get a better estimate of it after discarding units. That is, each individual has a true propensity score that doesn't depend on who is in the sample; for the units dropped, their first estimate is the best estimate of it we have for them, and for the units retained the second estimate is the best estimate of it we have for them. So the returned propensity scores in `distance` are the best estimate we have for each unit, even though those estimates come from different models. I don't actually think this reasoning holds to scrutiny, though; if a unit has a non-0.5 propensity score but the common support restriction yields a perfectly balanced sample, the re-estimated propensity score for that unit if retained will be .5, in which case the re-estimated propensity score is not the best estimate.

I don't really know how to proceed with this one. One option would be to report both sets of propensity scores. Another would be to generate predicted values for the dropped units using the re-estimated model fit to the retained units. I have big plans for more sophisticated overlap/common support functionality, but that is a long way off. I'll continue to think about it and would love to hear your or anyone else's thoughts on the matter, including what you as a user expect to see and want to see.
