### ISSUE TITLE
Matrix of matches if replace = TRUE

### ISSUE THREAD

**Issue by peisenha** [kosukeimai/MatchIt#159]
Dear Team, when running `matchit(..., replace=TRUE, estimand="ATT")` I expect the same control unit matched with different treated units. However, it looks like the same control unit is matched repeatedly with the same treated unit as well? Any guidance on how to interpret this is highly appreciated. Thank you very much in advance!

See example code and output for details:

![image](https://user-images.githubusercontent.com/3607591/230667533-1d03798e-6bc6-4b29-b2f4-6f7c3ab531f1.png)

**Comment by ngreifer** [comment]
This is a bug that has already been fixed on the development version, which you can install using `remotes::install_github("ngreifer'MatchIt")`. It will be up on CRAN soon.

**Comment by peisenha** [comment]
Dear @ngreifer , thank you very much for the swift update. Is this information used to, for example, construct the matched data frame during the call of `match.data()`? Or is this more or less a cosmetic issue that does not have any immediate consequences downstream? Thanks again! Best, @peisenha

**Comment by peisenha** [comment]
Thanks!
