### ISSUE TITLE
Travis build failures

### ISSUE THREAD

**Issue by cfhammill** [kosukeimai/MatchIt#16]
Travis builds are failing due to dependency WhatIf not being available. The problem is a broken Amelia build (https://travis-ci.org/kosukeimai/MatchIt/builds/267596888#L3139). The real issue RcppArmadillo requires a better gcc (https://travis-ci.org/kosukeimai/MatchIt/builds/267596888#L2510). I think you can get a better gcc easily by switching to building against ubuntu trusty. This is probably safer than trying to upgrade gcc via apt on precise. There will probably be errors related to packages being built with different compilers if you go the later route. 

To build against trusty you could put the following at the top of your .travis.yml

```
matrix:
  include:
    -  os: linux
       dist: trusty
```

(my package for reference https://github.com/cfhammill/RMINC/blob/master/.travis.yml#L1)

**Comment by kosukeimai** [comment]
Thanks @cfhammill   What about simply adding `dist: trusty` to `.travis.yml` ?

**Comment by cfhammill** [comment]
Not sure, worth a shot.

**Comment by kosukeimai** [comment]
The approach seems to work fine on the main branch.  Accordingly, I'm closing this issue.
