### ISSUE TITLE
Calculation of weights

### ISSUE THREAD

**Issue by peisenha** [kosukeimai/MatchIt#161]
Dear Team, I am currently studying the calculation of the matching weights and wanted to report / understand the following output which appears to be at odds with the [documentation](https://kosukeimai.github.io/MatchIt/reference/matchit.html#how-matching-weights-are-computed).

I am running the following analysis  on the Lalonde dataset:

![image](https://user-images.githubusercontent.com/3607591/231271343-f9016b81-4d5c-4096-a56f-a37ffc1b49d0.png)

The information provided in the two data frames `df_data` and `df_getm` is identical but for the `weights` column.

![image](https://user-images.githubusercontent.com/3607591/231271784-8a0bee6b-c2f9-4ac1-863e-3bcb729addda.png)

![image](https://user-images.githubusercontent.com/3607591/231271933-4989e871-3020-4e42-859f-7ae489162cf0.png)

Using the information from the documentation referenced above, I expected the weights to be 0.5 for the control units as in `df_get`. However, they appear to be 1.0 in `df_data`. I would highly appreciate if you could let me know what I am missing here. Thanks a lot in advance for your help and swift responses!

**Comment by ngreifer** [comment]
Did you read the [documentation](https://kosukeimai.github.io/MatchIt/reference/match.data.html) for `get_matches()`, which explains how the weights are computed? If not, please do so and let me know if it still isn't clear.

**Comment by peisenha** [comment]
I see, thanks, I was looking at the documentation of `matchit()` and thought the description on how to calculate the weights there applies to `get_matches()` and `match.data()`.

**Comment by ngreifer** [comment]
I agree that it is confusing that the weights are not equal. This is primarily because of the final step of estimating the weights in `matchit()`, which involves dividing the weights by their mean. In future versions of `MatchIt`, that may not be the case. In practice estimates should be the same regardless, but this issue has come up [several](https://github.com/kosukeimai/MatchIt/issues/155) [times](https://github.com/kosukeimai/MatchIt/issues/83).

**Comment by peisenha** [comment]
Thank you for the information. Looking at your answer, the other issues you reference, and the vignette "Estimating Effects After Matching: Matching with replacement", I had the impression that it does matter which data frame I use to compute the point estimate and standard errors. While I was able to confirm that for the point estimates, I am running into an issue with the standard errors in the case of matching with replacement. Did I understand the your statement and the documentation correctly, i.e. it does not matter which data frame I use or am I missing important nuances here? See below for a case where the standard errors are different. 

![image](https://user-images.githubusercontent.com/3607591/231797032-bf88791f-0fc7-4636-8c5a-161ba471e702.png)
