### ISSUE TITLE
"Simple" exact 1:1 matchint not working

### ISSUE THREAD

**Issue by buhtz** [kosukeimai/MatchIt#164]
[X-Post on StackOverflow](https://stackoverflow.com/q/76055826/4865723)

With your help I did Propensity Score Matching in the past. Now I need to do "simple" 1 to 1 exact matching. But It do not work.
I would expect that the resulting data consist of two groups with the same size. But in my MWE it looks like this where the groups are not of thes same size.

    Sample Sizes:
                  Control Treated
    All             48.        52
    Matched (ESS)   16.66      31
    Matched         34.        31
    Unmatched       14.        21
    Discarded        0.         0

I'm sure I misunderstand something here.

Here is an MWE constructing sample data.

    # see: https://cran.r-project.org/web/packages/MatchIt/vignettes/MatchIt.html
    library("MatchIt")
    
    set.seed(0)

    df <- data.frame(
        group = sample(c('X', 'Y'), 100, replace = TRUE),
        foo = sample(LETTERS[1:4], 100, replace = TRUE),
        bar = sample(10:20, 100, replace = TRUE)
    )
    
    m.out <- matchit(
        group ~ foo + bar,
        data = df,
        method = "exact",
    )
    
    summary(m.out)
    
    # get data
    m.data <- match.data(m.out)
    
    head(m.data)

The head of the resulting data.

    > head(m.data)
       group foo bar   weights subclass
    1      Y   A  18 1.0000000        1
    2      X   D  19 1.4623656        2
    3      Y   D  19 1.0000000        2
    5      X   A  11 0.5483871        4
    8      X   C  11 1.0967742       17
    14     X   C  17 0.5483871       16

In my expectation the resulting data should look like this, where each pair has the same value in `foo` and `bar`.

        group foo bar
    1       Y   A  18
    37      X   A  18
    
    2       X   D  19
    3       Y   D  19
    
    5       X   A  11
    28      Y   A  11
    
    6       Y   A  12
    10      Y   A  12
    
    7       X   A  10
    92      X   A  10

    ...

**Comment by ngreifer** [comment]
That code doesn't do "simple" 1:1 exact matching. The `MatchIt` [vignette](https://kosukeimai.github.io/MatchIt/articles/matching-methods.html) on matching methods explains what exact matching is. It is a form of stratification, not a form of pairing. See [my answer on SO](https://stackoverflow.com/a/71941588/6348551) for how to do 1:1 exact matching.

**Comment by buhtz** [comment]
I really appreciate your help and patience. Missing basic knowledge on my side does make it hard for me to get deeper into the topic. Your SO link does give me the code to solve the problem.

But I still don't understand. You tell me that there is a difference between "simple 1:1" (pair matching) and "exact" matching. Can you show me a data example to illustrate that difference? I also do know what stratification is but don't know how that fits into the context of matching. For example in my original data I stratified the age into 5year groups and using that variable as one of the covariates to match.

**Comment by buhtz** [comment]
Let me mention that in my real data this time I both groups are nearly the same size. Each group has more then 300.000 persons. It screams to get matched 1 to 1. I assume after "exact 1 to 1 pair matching" there will be 50.000 to 150.000 persons left.

> We can use your data to discuss the difference between 1:1 exact matching and (general) exact matching. When I say exact matching is a stratification method, I mean that strata are formed based on a complete cross of the variables specified. So in your example, the strata are
> 
> ```
> foo = A | bar = 10
> foo = A | bar = 11
> foo = A | bar = 12
> ...
> foo = B | bar = 10
> foo = B | bar = 111
> ...
> foo = D | bar = 19
> foo = D | bar = 20
> ```

> In general, pair matching (e.g., nearest neighbor matching) involves creating pairs of treated and control units based on how far apart the units are based on some distance metric (e.g., the propensity score difference or Mahalanobis distance). The result is a set of pairs, each with one treated and one control unit that are close together on the matching variables. If we request an exact matching constraint, then units must have exactly the same values of the variables to be able to be paired. Any treated unit that doesn't have a matched control unit (either because there are no control units with its covariate values or because all such control units have already been used up by other treated units) are dropped, and any control unit that is not paired with a treated unit is dropped. This seems to be what you are expecting from exact matching.

Exactly that is what I expect form exact matching. Still not sure how the correct term I should use for "exact 1 to 1 paring matching". ;)

Thanks in advance for your explanations. My problem is to transform the basic concepts of the different matching methods to the practice. I need a tutorial using sample data. The basic concepts are not difficult for me. But I think of it like a programmer and not like a statistician. There are to many math terms for me. ;)

Maybe I should play around and creating my own tutorial to improve my understanding.
