### ISSUE TITLE
eCDF

### ISSUE THREAD

**Issue by raffaem** [kosukeimai/MatchIt#166]
Maybe I'm pedantic, but MatchIt [vignette](https://kosukeimai.github.io/MatchIt/articles/MatchIt.html) say that eCDF stands for "empirical cumulative *density* function", while [Wikipedia](https://en.wikipedia.org/wiki/Empirical_distribution_function) defines it as "empirical cumulative *distribution* function", and if you [look up "cumulative density function"](https://en.wikipedia.org/wiki/Cumulative_density_function) you'll find out that "cumulative" and "density" contradicts each other.

**Comment by ngreifer** [comment]
You're right, thanks for catching that.
