### ISSUE TITLE
Optimal matching throws an error about the data argument when discarding is used

### ISSUE THREAD

**Issue by NikNakk** [kosukeimai/MatchIt#171]
When some cases or controls are discarded and exact matching is used, the `matchit2optimal` function may fail. The problem arises because of the following lines of code from [R/matchit2optimal.R](https://github.com/kosukeimai/MatchIt/blob/master/R/matchit2optimal.R):

```
ex <- factor(exactify(model.frame(exact, data = data), 
  sep = ", ", include_vars = TRUE)[!discarded])
```
...
`t_df <- data.frame(treat)`
...
```
matchit_try({
  p[[e]] <- do.call(optmatch::fullmatch, c(list(mo_, 
    mean.controls = ratio_, min.controls = min.controls_, 
    max.controls = max.controls_, data = t_df[ex == 
      e, , drop = FALSE]), A))
}, from = "optmatch")
```

It can be seen that `ex` is filtered based on `discarded`, whereas `t_df` is based on the unfiltered `treat`. When `ex == e` is used to select specific rows of `t_df`, `ex` is no longer lined up to `t_df` and so the rows returned will be wrong as soon as there are any gaps related to discarded cases or controls.

The error message seen is:
```
Error in matchit(elig_biologic ~ demog_age + elig_diagnosis + IMM, tmp,  : 
  (from optmatch) Some elements of the distance matrix are not found in the data argument.
```

**Comment by ngreifer** [comment]
Thank you so much for the bug report and fix. I have incorporated this into the development version, which you can install using 
```r
remotes::install_github("ngreifer/MatchIt")
```
I have also credited you for the fix in the NEWS file, though I'm not going to accept the pull request.
