### ISSUE TITLE
Cardinality matching doesnt work with HiGHS

### ISSUE THREAD

**Issue by MkGrjk** [kosukeimai/MatchIt#177]
the error message says: 
Error in `matchit()`:
! The argument to `solver` should be one of "glpk",

**Comment by ngreifer** [comment]
The version that supports `"highs"` was just submitted to CRAN yesterday, so it will take a bit of time to fully update. Try re-installing `MatchIt`, restarting your R session, and running `matchit()` again. If R asks you to install the package from source, you have to say Yes to get the most updated version of the package. If you wait a few days, all versions of `MatchIt` on CRAN should have this option enabled.
