### ISSUE TITLE
Issue with optimal matching method

### ISSUE THREAD

**Issue by jaySf** [kosukeimai/MatchIt#18]
Using the "optimal" method with option `ratio = 2` we get this warning:
```
Warning message:
In optmatch::fullmatch(d, min.controls = ratio, max.controls = ratio,  :
  Without 'data' argument the order of the match is not guaranteed
    to be the same as your original data.
```
In [Ho et al. (2011:11)](http://r.iq.harvard.edu/docs/matchit/2.4-20/matchit.pdf) it is stated:
> We conduct 2:1 optimal ratio matching based on the propensity score from the logistic regression.

Whereas 2013 in a [mailing list](https://lists.gking.harvard.edu/pipermail/matchit/2013-August/000538.html) Kosuke states:
> I think that the problem is you have "ratio = 2".  optimal matching may not work with that option.

Getting the error by exactly copy-pasting the code from the manual mentioned above and which is downloadable at [Garry King's MatchIt site](https://gking.harvard.edu/matchit):
```
library(MatchIt)
data("lalonde")
m.out <- matchit(treat ~ re74 + re75 + age + educ, data = lalonde, 
              method = "optimal", ratio = 2)
```
This is quite contradictory and creates confusion, e. g. [here ](https://stackoverflow.com/questions/28138581/optimal-matching-error-warning-but-the-output-seems-fine)and [here](https://stackoverflow.com/questions/32502078/matchit-warning-order-of-the-match-is-not-guaranteed).

Please could you clarify that? Thanks a lot!

**Comment by JSchork** [comment]
I had the same problem. A clarification of the issue would be highly appreciated!

**Comment by kosukeimai** [comment]
I don't think you need to worry about this.
