### ISSUE TITLE
Match selected samples from both control and treatment cohort

### ISSUE THREAD

**Issue by ethanbama** [kosukeimai/MatchIt#182]
I have a control and treatment cohort, and I want to select a group of samples from the control, and another group of samples from the treated group. How can I match these selected samples in the treatment cohort to the treated cohort, and visa versa match the selected samples in the treated cohort to the control cohort?

**Comment by ngreifer** [comment]
I'm not exactly sure what you're trying to do or why you're trying to do it. Could you elaborate or show me an example of a study that does this?

**Comment by ethanbama** [comment]
![bitmap](https://github.com/kosukeimai/MatchIt/assets/150479055/c43d4622-10a1-457d-9518-ea1e3d727efa)
I put a diagram here. There are A and B cohorts, I want to retain the blue individuals from these cohorts for reasons like gene mutations. I want to match the age and gender of the selected individuals in these two cohorts. Hope this clarifies the question. 

Many thanks.

**Comment by ngreifer** [comment]
I'm sorry, I still don't understand. If you only want to match the blue individuals, why not just exclude everyone else from the sample? I don't see how this is different from regular matching. What kind of logistic regression model are you fitting? (What are the outcome, treatment, and other predictors?) Also, if you are matching by incorporating the outcome, you should look into case-control matching, which is specifically designed for rare outcomes.

**Comment by ethanbama** [comment]
Thank you very much for your quick response. The case-control matching is what I need here.
