### ISSUE TITLE
Issue with genetic matching method

### ISSUE THREAD

**Issue by jaySf** [kosukeimai/MatchIt#19]
In my own analysis and _even_ when running `demo("genetic")` following warning occurs (at the very end after identifying variables):
```
Warning messages: ----
#   1: In Matching::GenMatch(tt, cbind(dd, xx), M = ratio, ...) :
#   The key tuning parameters for optimization were are all left at their default
#   values.  The 'pop.size' option in particular should probably be increased for
#   optimal results.  For details please see the help page and
#   http://sekhon.berkeley.edu/papers/MatchingJSS.pdf
```
The issue is also mentioned in a [mailing list](https://lists.gking.harvard.edu/pipermail/matchit/2014-January/000571.html) w/o answer.

Since the issue also occurs in the demo it might be some kind of bug.
Please could you check that? Thanks!

**Comment by kosukeimai** [comment]
This should be a question for the author of GenMatch
