### ISSUE TITLE
Predetermined subsample size

### ISSUE THREAD

**Issue by igormarchetti** [kosukeimai/MatchIt#197]
Is it possible to specify the sample size of the two groups that I'm trying to match for specific covariates? I've managed to obtain two subgroups of the same size, but I would find it very usesful to calibrate to a predetermined sample size. Is it currently possible with the MatchIt package?

**Comment by ngreifer** [comment]
You can't with `MatchIt`, but you can using `MatchingFrontier`. It integrates with `MatchIt` to allow you to perform matching using `MatchIt` then discard one pair at a time until you reach your desired sample size, opun which you can extract the matched sample. See [here](https://iqss.github.io/MatchingFrontier/) for general information on the package. The functionality I mentioned is described [here](https://iqss.github.io/MatchingFrontier/reference/makeFrontier.matchit.html).
