### ISSUE TITLE
Imputed Data for Matching

### ISSUE THREAD

**Issue by linem7** [kosukeimai/MatchIt#199]
Hi,

I was wondering if it's possible to use multiply imputed data (generated by the mice package) for matching when I have some missing data in my covariates. 

I appreciate your time and help on this. I understand that I might need to look into mice support, but I thought you might have insights on this.

Thanks in advance for your assistance.

Best regards,
Lin

**Comment by ngreifer** [comment]
Use the `MatchThem` package, which contains wrappers for functions in `MatchIt` for use with multiply imputed data.

**Comment by linem7** [comment]
Thank you very much! I really appreciate your help. Thanks again!
