### ISSUE TITLE
Matching when certain matches are forbidden

### ISSUE THREAD

**Issue by GalAmedi** [kosukeimai/MatchIt#203]
Hey. I have a context in which the sampled units are spatial units, and the treatment is determined by their location (that is, close units will be very similar in both their treatment status and in most of the covariates I would like to match on).

I would like to balance the sample using matching, while not allowing nearby units to be matched. This can be done with one of two conditions:
(1): don't allow matching within a more broadly defined region.
(2): don't allow matching for units with a physical distance of less than $X$ between them.

Is there any way to implement such a procedure in MatchIt?

Thanks for a great package,
Gal

**Comment by ngreifer** [comment]
There's no way to do this automatically in `MatchIt`. The `antiexact` option forbids matches with the same level of a variable, but not based on a distance between them. `matchit()` does accept arbitrary distance matrices to the `distance` argument, though, and you can create a custom distance matrix for the variables you want to match on and then manually forbid any matches you don't want to allow by setting the distance to `Inf`.

**Comment by GalAmedi** [comment]
Thank you Noah, that's very helpful. I'm closing the thread.

Gal
