### ISSUE TITLE
lack of rownames in dataframe crashes caliper matching

### ISSUE THREAD

**Issue by lmiratrix** [kosukeimai/MatchIt#21]
See demo script, below.  matchit() fails in first call.  Adding rownames fixes it in second call.  This is due to some extraction breaking deep in the guts of matchit()

# Small test case of possible bug?

library( MatchIt )

make.dat = function( p, N, beta0 = -1, beta1=1 ) {
    X = matrix( rnorm( p * N ), ncol = p )
    pi = arm::invlogit( beta0 + beta1 * X[,1] )
    Z = 0 +( runif( N ) <= pi )

    colnames(X) = paste( "X", 1:p, sep="" )
    df = as.data.frame( X )
    df$Z = Z
    df
}

mydat = make.dat( 3, 100 )
head( mydat )
str( mydat )

m.out <- matchit(Z ~ X1 + X2 + X3, data = mydat, method = "nearest",
                     caliper = 0.2, mahvars = c("X1","X2") )

rownames( mydat ) = paste( "R", rownames(mydat), sep="" )
m.out <- matchit(Z ~ X1 + X2 + X3, data = mydat, method = "nearest",
                 caliper = 0.2, mahvars = c("X1","X2") )

**Comment by ngreifer** [comment]
This has been fixed, thank you!
