### ISSUE TITLE
Error with ratio > 1 and 'genetic' matching

### ISSUE THREAD

**Issue by martinzuba** [kosukeimai/MatchIt#25]
I have encountered an error and possibly a bug in the `MatchIt` package. 

The error occurs when using genetic matching with a ratio > 2.

The error message reads:
```
 Error in out[out[, 1] == tind[i], 2:(ratio + 1)] : 
  subscript out of bounds 
```
Using the debugger, I have traced back the problem to the following section of code:
```
out <- Matching::GenMatch(tt, cbind(dd, xx), M = ratio, 
    ...)$matches
  mm <- matrix(0, nrow = n1, ncol = max(table(out[, 1])), 
    dimnames = list(tlabels, 1:max(table(out[, 1]))))
  for (i in 1:n1) {
    tmp <- labels[c(out[out[, 1] == tind[i], 2:(ratio + 
      1)])]
    if (length(tmp) < ncol(mm)) 
      tmp <- c(tmp, rep(NA, ncol(mm) - length(tmp)))
    mm[i, ] <- tmp
  }
```

`out` is an array where the first column is treatment units, the second column is matched control units, and the third column is some weight (?), i.e. 1 divided by the number of matched control units, where the number of matched control units is greater or equal to the `ratio` parameter. 

Note that the data format is `long`, that is, every treatment unit has as many rows as there are matched control units, at least `ratio`.

`mm`, in contrast, is a matrix where again rows are treatment units, but columns are matched control units. The number of columns is thus equal to the largest number of control units matched to a treatment unit.

Since the data format of `out` is long, and `ratio` is larger than 2 (e.g. 5), the line
```
tmp <- labels[c(out[out[, 1] == tind[i], 2:(ratio + 
      1)])]
```
will result in an error, since it will try to access columns 2:6 of the `out` array, which does not exist.

I believe that this line should read 
```
tmp <- labels[c(out[out[, 1] == tind[i], 2])]
```
and in my version it seems to work fine with that change.

**Comment by ngreifer** [comment]
This has been fixed. Thank you!
