### ISSUE TITLE
QQPlot Error with nearest neighbor, exact, and ratio>1

### ISSUE THREAD

**Issue by mosheradinsky** [kosukeimai/MatchIt#27]
QQ plotting nearest neighbor matching results using the "exact" option on a factor and ratio>1 produces the error:
`Error in jitter(m.xi) : 'x' must be numeric `
Code to reproduce the error:
```
library(MatchIt)
data(lalonde)
lalonde$married<-as.factor(lalonde$married)
m.out <- matchit(treat ~ re74 + re75 + educ + age,
                 data = lalonde, ratio = 2, method = "nearest", exact=c("married"))
plot(m.out, type = "QQ", interact = F)
```
A modification to line 34 of matchit.qqplot.R seems to fix the issue:
Change:
`m.covariates <- x$X[c(t.plot, c.plot),]`
to:
`m.covariates <- X[c(t.plot, c.plot),]`

**Comment by ngreifer** [comment]
This has been fixed.
