### ISSUE TITLE
How to deal with missing values in variables that are used for matching ？

### ISSUE THREAD

**Issue by mylanhong** [kosukeimai/MatchIt#28]
Hello，when we have missing values in variables that are used for matching and these variables largely influence the imbalance, how can we deal with it ? Is there any alternative method ?

**Comment by kosukeimai** [comment]
You can include the indicator variable for missingness as a covariate.

**Comment by mylanhong** [comment]
@kosukeimai Thanks for the reply. It is helpful! In addtion, although we can get 'Mean Diff' using the summary() function with matchit object, how can i calculate the SMD (STD Mean Difference) for each variable before and after matching with MatchIt package?

**Comment by kosukeimai** [comment]
See https://r.iq.harvard.edu/docs/matchit/2.4-20/matchit.pdf
