### ISSUE TITLE
get_matches() selects wrong rows if row names are non-consecutive numbers

### ISSUE THREAD

**Issue by tlmcmurry** [kosukeimai/MatchIt#29]
Dear MatchIt Team,

When the input data frame has numeric row names that aren’t consecutive (which can arise if you drop rows with missing data), get_matches() picks up the wrong rows without warning.  In the example below get_matches() picks up 2 non-existant rows and gets the rest of the rows wrong as well. 

Thanks for a very helpful package!
Tim McMurry

```R
library(MatchIt)
set.seed(1234)
df <- data.frame(group = rep(c("A", "B"), times = c(10, 20)),
			  x = rnorm(30) + rep(c(0, 1), times = c(10, 20)))
df$x[c(7, 11, 12)] <- NA #make some missing data

matchit(I(group == "A") ~ x, data = df) #doesn't work because of NAs
dfcomp <- model.frame(group ~ x, data = df) #drop missings, keep rownames
dfcomp <- df[!is.na(df$x), ] #alternative to line above, same problem

mm <- matchit(I(group == "A") ~ x, data = dfcomp) #works
summary(mm)
get_matches(mm, dfcomp) #Picks up non-existant rows, no warnings

#Correct matches
df[c(rownames(mm$match.matrix), mm$match.matrix[,1]),]
```

**Comment by alexWhitworth** [comment]
Interesting. Thanks for reporting... On a quick look, it appears a reasonably straightforward debug (and need for new test cases); but I'll have to look at it more closely over the weekend. 

Appears to be related to this logic: https://github.com/kosukeimai/MatchIt/blob/master/R/class_functions.R#L133-L147

**Comment by ngreifer** [comment]
`get_matches()` has been restructured and this problem no longer occurs. The correct units are now returned.
