### ISSUE TITLE
optmatch

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/MatchIt#3]
@alexWhitworth CRAN doesn't like a new submission because MatchIt now requires optmatch, which does not have a FOSS license.  Is it possible to make optmatch in a "Suggests" category?

**Comment by alexWhitworth** [comment]
@kosukeimai That shouldn't be a problem. Do you wish to do it or have me do so?

**Comment by kosukeimai** [comment]
Would you mind doing it since you know the structure of the new code well.  Thanks.
