### ISSUE TITLE
Weird error on exact matching with nearest neighbor

### ISSUE THREAD

**Issue by libgober** [kosukeimai/MatchIt#31]
I'm running into an issue with applying exact matching on some covariates and nearest neighbor matching on others. Here is the call

    data = read.csv("trouble_shooting.csv")
    m.out = matchit(treated~ 
                  adjusted_basic_pay + age_range,
                data,
        method='nearest',
        distance='mahalanobis',
        exact='age_range',
        replace=F)

This is the result:

    Error in Ops.data.frame(exact[itert, k], exact[clabels, k]) : 
       ‘!=’ only defined for equally-sized data frames

Link to file here: https://www.dropbox.com/s/ukkx7rph7mmcpso/trouble_shooting.csv?dl=0

**Comment by ngreifer** [comment]
This has been fixed. Thank you.
