### ISSUE TITLE
Warning for reserved variables - distance

### ISSUE THREAD

**Issue by swinersha** [kosukeimai/MatchIt#32]
When generating matched the dataset using `match.data(m.out)` an error is thrown when the data contains a reserved variable (e.g. distance):
`m.data<-match.data(m.out)
Error in match.data(m.out) : 
  invalid input for distance. choose a different name.`
The error warning is not very intuitive. A slightly more verbose warning would be useful. I also feel that distance is likely to be a common variable name in matching so it would be good to avoid failure.

**Comment by ngreifer** [comment]
Thank you for this suggestion. The error message is now more informative.
