### ISSUE TITLE
The nearest.R demo doesn't generate a really matched data

### ISSUE THREAD

**Issue by hlblade** [kosukeimai/MatchIt#33]
Hi
I am studying to use MatchIt package to do  PSM. But when I use the nearest.R in the demo fold to try to generate a mached data. Then I use the table1 package to review the data. 

There are still big difference between groups, why?
`library(MatchIt)
data(lalonde)
lalonde$treat    <- factor(lalonde$treat, levels=c(0, 1), labels=c("Control", "Treatment"))
lalonde$black    <- factor(lalonde$black)
lalonde$hispan   <- factor(lalonde$hispan)
lalonde$married  <- factor(lalonde$married)
lalonde$nodegree <- factor(lalonde$nodegree)
lalonde$black    <- as.logical(lalonde$black == 1)
lalonde$hispan   <- as.logical(lalonde$hispan == 1)
lalonde$married  <- as.logical(lalonde$married == 1)
lalonde$nodegree <- as.logical(lalonde$nodegree == 1)
m.out <- matchit(treat~age+educ+black+hispan+married+nodegree+re74+re75+re78, data = lalonde,method = "nearest")
lalonde<-match.data(m.out)
library(table1)
rndr <- function(x, name, ...) {
  if (length(x) == 0) {
    y <- lalonde[[name]]
    s <- rep("", length(render.default(x=y, name=name, ...)))
    if (is.numeric(y)) {
      p <- t.test(y ~ lalonde$treat)$p.value
    } else {
      p <- chisq.test(table(y, droplevels(lalonde$treat)))$p.value
    }
    s[2] <- sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
    s
  } else {
    render.default(x=x, name=name, ...)
  }
}

rndr.strat <- function(label, n, ...) {
  ifelse(n==0, label, render.strat.default(label, n, ...))
}

table1(~ age + black + hispan + married + nodegree + re74 + re75 + re78 | treat,
       data=lalonde, droplevels=F, render=rndr, render.strat=rndr.strat, overall=F)`

**Comment by ngreifer** [comment]
1:1 nearest neighbor propensity score matching doesn't always work if there aren't good matches. In this dataset, it just happens to be the case that this form of matching doesn't work very well. Other forms of matching, like full matching and matching with replacement, do yield much better balance. This is demonstrated in the new `vignette("MatchIt")`.
