### ISSUE TITLE
Caliper widths are on propensity score scale rather than logit scale for distance="logit"

### ISSUE THREAD

**Issue by salauer** [kosukeimai/MatchIt#36]
[Austin (Pharmaceutical Statistics, 2011)](https://onlinelibrary.wiley.com/doi/full/10.1002/pst.433) recommends using a caliper width of 0.2 of the standard deviation of the logit of the propensity score, because it is more likely to be normally distributed. It appears that the caliper width calculated in `matchit(..., distance="logit")` is based on the propensity scores themselves and not the logit of these propensity scores. I'm not sure if this is intentional, but if not, it could be remedied by fixing line 3 of `distance2glm.R` to
```
return(list(model = res, distance = predict(res, response="link")))
```
If this was intentional, I'd appreciate a link to the literature for justification.

Thanks,
Steve

**Comment by ngreifer** [comment]
To use the logit of the propensity scores, set `distance = "linear.logit"`. Although it's true that the logit often has good performance, in some datasets a caliper on the raw propensity score may be effective as well, so both should be checked. There isn't one universally best method.

**Comment by salauer** [comment]
Oh that's good to know! Thanks for the quick reply!
