### ISSUE TITLE
Reproducibility Error

### ISSUE THREAD

**Issue by priyankapri** [kosukeimai/MatchIt#38]
Hi,

I have been lately using the Matcit package. After setting a seed number, I ran the query to match 1:4 with caliper 0.25, no replace and it does contain some variable for exact matching and I re-ran again the same query using exactly the same seed number and other conditions but on a later date likely after month. It came to my surprise that my total matching data was not the same. It automatically took away 4 patients out of control and upon re-running it took 2 patients from the cases. It does not give me any error per se as the query runs smoothly. But matching sample differs. 
Please let me know how I can fix this.

Priyanka

**Comment by ngreifer** [comment]
Please see [this answer](https://stackoverflow.com/questions/47199415/is-set-seed-consistent-over-different-versions-of-r-and-ubuntu/56381613#56381613) on SO and let me know if it helps. If you upgraded R between then and now, the way R performs random sampling by default may differ between the old version and the one you are currently running.

**Comment by priyankapri** [comment]
No updates were performed.

**Comment by ngreifer** [comment]
If you re-run the analysis again with the same seed, do you get results identical to the most recent results? Or do the results change each time (even when using the same seed)?

**Comment by priyankapri** [comment]
When I re-ran the analysis using seed numbers in that session I did get the same results as the most recent results. But I am not sure after a while will it be the same. How can i preserve this?

**Comment by ngreifer** [comment]
`MatchIt` just uses the same random sampling functions that other packages in R use; there is nothing special about the implementation here, so it's hard to provide any advice other than to set a seed and record the version of R and `MatchIt` that you used to perform the analyses. I'm sorry you were unable to reproduce your results, but I don't think there is anything we can do about it.

In the updated version of `MatchIt` coming soon, there are no random processes with nearest neighbor matching, so a seed will not have to be set in the future when using caliper matching (whereas currently, certain stochastic actions are taken in the matching process). This will encourage replicability across runs. It will not let you reproduce your original results, though. I have no suggestions on how to replicate your original results except to ensure everything, including the seed and the versions of R and `MatchIt`, is the same as in the original analysis.
