### ISSUE TITLE
Can I ask a follow-up question?

### ISSUE THREAD

**Issue by youblue** [kosukeimai/MatchIt#49]
Can I ask a follow-up question?

With the new behavior of caliper, does it mean that the matched controls selected when using caliper are always a subset of those selected without using caliper, given all the other parameters are the same (using method = "nearest")?
Since caliper seems only helps to remove those "outliers" but for those ones that can match well within calipers, they are always the nearest ones to the treated subjects (and this is a certain), there's no randomness any more? 

Thank you so much!

_Originally posted by @youblue in https://github.com/kosukeimai/MatchIt/issues/48#issuecomment-730772979_

**Comment by ngreifer** [comment]
Basically yes. I'll explain how matching is implemented.

One treated unit at a time, we check which controls are eligible to be matched with that treated unit. If matching without replacement, any previously matched control units are ineligible. If exact matching, any control units not in the same stratum as the treated unit are ineligible. If a caliper is present, any control units outside the caliper are ineligible. What remains is a pool of remaining eligible control units for that treated unit. If that pool is empty, the treated unit does not get a match. **If the pool is not empty, the control unit in the pool that is closest to the treated unit gets matched to that treated unit.** Then we move on to the next treated unit. 

This is the same way matching occurred in the older versions of `MatchIt`, except that the bolded sentence would read "If the pool is not empty, a randomly selected control unit in the pool gets matched to that treated unit". You can see how the new behavior improves the quality of matches and enhances replicability moving forward. 

I'm pretty sure the set of matched controls with a caliper is a subset of the set of matched controls without a caliper, but they will not necessarily be matched to the same treated units.

**Comment by youblue** [comment]
It's great to get confirmation from you. Super helpful! 
Thank you so much!

**Comment by ngreifer** [comment]
Glad it was helpful! Feel free to ask if anything else comes to mind.
