### ISSUE TITLE
compatibility with Zelig

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/MatchIt#5]
The following error has been reported by multiple users:

```
demo(analysis)

> ate.all <- c(s.out1$qi$att.ev, -s.out2$qi$att.ev)
Error in s.out1$qi$att.ev : object of type 'closure' is not subsettable
```

**Comment by jaySf** [comment]
I am facing the issue, too. Regards.

**Comment by albertostefanelli** [comment]
might be that this could replace the above command 

`c(s.out1$sim.out[[1]][1][[1]][[1]], -s.out2$sim.out[[1]][1][[1]][[1]])`
