### ISSUE TITLE
match.data not working when matchit is called from within a function

### ISSUE THREAD

**Issue by icrandell** [kosukeimai/MatchIt#53]
Good afternoon,

I'm comparing sets of multiple matching strategies on different data sets, and so I've found it convenient to use a wrapper function for matchit to facilitate looping. Mostly it works fine, but I've run into an error when I try to use match.data() on a matchit object returned from my wrapper. See a minimal reprex below:

`library(MatchIt)
data(lalonde)
match1 = matchit(treat ~ age + educ + race + married + nodegree, data = lalonde)
match.data(match1)

match_with_varying_data = function(fmla, matchData){
  matchit(fmla, data = matchData)
}

match2 = match_with_varying_data(fmla = formula("treat ~ age + educ + race + married + nodegree"), 
                                 matchData = lalonde)
match.data(match2)
`

The issue seems to be that match.data() is looking in object$call$data for the name of the dataset. For match1$call$data it returns "lalonde," which it then finds globally. However, in match2$call$data it finds matchData, the name of the data in the wrapper's environment. Interestingly, this error does not appear if I use a wrapper that only uses a data argument, and not a formula argument. For instance, this works fine:

`match_with_varying_data_no_fmla = function(matchData){
  matchit(treat ~ age + educ + race + married + nodegree, data = matchData)
}

match3 = match_with_varying_data_no_fmla(matchData = lalonde)
match.data(match3)
`

I've managed a workaround, but this doesn't seem like the intended behavior. Thank you, and please see sessionInfo() below:

R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin18.7.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/openblas/0.3.10_1/lib/libopenblasp-r0.3.10.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MatchIt_4.0.1

loaded via a namespace (and not attached):
[1] compiler_4.0.2  backports_1.1.8 tools_4.0.2     Rcpp_1.0.5

**Comment by ngreifer** [comment]
Unfortunately, the way `match.data()` recovers the original dataset from the `matchit` object forces this problem to happen. As a solution, you can pass the dataset directly to `match.data()` to avoid this, as recommended in the `match.data()` documentation. In your case, you would call 
```
match.data(match3, data = lalonde)
```
This prevents `match.data()` attempting to extract the data from the `matchit` object directly.

**Comment by icrandell** [comment]
Understood, I missed that recommendation in the documentation. I will gladly specify the proper dataset as an argument. Thanks!
