### ISSUE TITLE
Interaction terms are automatically excluded (?) when using newer version

### ISSUE THREAD

**Issue by ktak0715** [kosukeimai/MatchIt#55]
Hi there,

I have tried to implement matching based on a specification which includes interaction terms (age:educ in this case) as follows.

data("lalonde")
m.out1 <- matchit(treat ~ age:educ + I(age^2) + age + educ + race + married + nodegree + re74 + re75, data = lalonde,distance = "glm", link = "linear.probit")
summary(m.out1,standardize=TRUE)

However, after running this code, the covariate balance for age:educ is not shown although this did not happen when using an older version of MatchIt.

Ktak

**Comment by ngreifer** [comment]
Unfortunately, some tradeoffs were made when restructuring the `MatchIt` output, and processing interactions was one of the features dropped. I'll continue to look into options to retain it. To get the interaction back into `summary()`, you can supply it to the `addlvariables` argument using the formula syntax, as follows:
```
summary(m.out1, addlvariables = ~age:educ)
```

**Comment by ktak0715** [comment]
Thank you for your reply.
I have acknowledged the cause of this issue.
I will try the solution you suggested.
