### ISSUE TITLE
set.seed et last version of MatchIt

### ISSUE THREAD

**Issue by akiki2601** [kosukeimai/MatchIt#56]
Hi

Thank you very much for this great package.

There is maybe a bug with the last version of MatchIt. 

When I change set.seed() to adjust the matching. There is no change in the matching process thereafter. I tried to update my R (4.03), I also downgraded R... no change... I tried on a Mac, on Windows.... no change...

The problem is solved when I downgraded to MatchIt_3.0.2  

All my best

Antoine

PS: sorry if this issue is not correct. You do a great job thank you so much

**Comment by ngreifer** [comment]
Hi Antoine,

Thank you for the kind words. I'm not sure what you mean with this. Are you trying to replicate prior results that used an old version of `MatchIt`? See my explanations [here](https://github.com/kosukeimai/MatchIt/issues/51). If you are matching with a caliper and wondering why your results don't change when changing the seed with the new version but do change when using the old version, I discuss that [here](https://github.com/kosukeimai/MatchIt/issues/48) and [here](https://kosukeimai.github.io/MatchIt/news/index.html#method--nearest).

In the new version of `MatchIt`, there are no random processes when using nearest neighbor matching (unless `m.order = "random"`), so you should expect to see the same results when using different seeds. In older versions, there were a number of random processes, so results would differ depending on which seed was used. We reduced the number of random processes to enhance replicability. If you want to replicate old results, use an older version of the package.

Does this solve your problem?

Noah
