### ISSUE TITLE
match.data does not function with {purrr}

### ISSUE THREAD

**Issue by kristopherdelane** [kosukeimai/MatchIt#58]
nest_data <- lalonde %>% 
  group_by(race) %>%
  nest()

match_nested_data <- function(df){matchit(treat ~ age + re74 + educ + re75 + re78, 
                       data = {{df}},
                       method = "cem") }

cem_matchit <- map(.x = nest_data$data, .f = match_nested_data)

data <- map(cem_matchit, match.data)

**Comment by ngreifer** [comment]
Please see #53. This is an inherent limitation in `match.data()` but can be solved by supplying the `data` argument to `match.data()`.
