### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by kentarofukumotojp** [kosukeimai/MatchIt#59]
In the last page of the manual, "nn" appears twice in the "Value" section.

**Comment by ngreifer** [comment]
The Value section describes two output objects, `summary.matchit` and `summary.matchit.subclass`, both of which contain `nn`  components. You'll notice that all the other components appear to be duplicated as well.

**Comment by kentarofukumotojp** [comment]
Thanks, Noah!

************************************************************
**********************************
Kentaro FUKUMOTO, Ph. D.
Professor, Department of Political Science, Gakushuin University
http://www-cc.gakushuin.ac.jp/~e982440/index_e.htm
************************************************************
**********************************


2021年2月22日(月) 5:39 Noah Greifer <notifications@github.com>:
