### ISSUE TITLE
NAMESPACE Issue When Compiling CBPS

### ISSUE THREAD

**Issue by christianfong** [kosukeimai/MatchIt#62]
Hi Noah,

When I try to build CBPS, I am now getting an error from MatchIt.

Error: package or namespace load failed for 'MatchIt' in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
Error : package 'MatchIt' could not be loaded

Any idea what could be causing this error?

Thanks!
Christian

**Comment by ngreifer** [comment]
Interesting, I'm so sorry about this. I'll look into it now and see if I can fix it.

**Comment by ngreifer** [comment]
Have you tried the solution described [here](https://stackoverflow.com/questions/55925357/error-in-rbindinfo-getnamespaceinfoenv-s3methods-when-installing-factoex)?

**Comment by christianfong** [comment]
Thanks so much, Noah!  That put me on the right track.
