### ISSUE TITLE
match.matrix NULL?

### ISSUE THREAD

**Issue by kumarde** [kosukeimai/MatchIt#63]
Hi all,

Thanks for an excellent package. I am trying to extract the exact control / treatment matches made through `matchit`, and I thought I could get this by simply running:

`m.out1 <- matchit(...)`
`attr(m.out1, "match.matrix")`

Unfortunately, all the attributes in`m.out1` are NULL. Is this expected behavior? Am I doing something horrendously silly? I'm new to R so any pointers are helpful here.

Thanks!

**Comment by ngreifer** [comment]
`match.matrix` is not an attribute, it's a component of the output object itself. So you should run `m.out1$match.matrix` to get it. Note that not all methods will produce one.

**Comment by kumarde** [comment]
Thank you, this is very helpful! :)
