### ISSUE TITLE
threshold in propensity score matching

### ISSUE THREAD

**Issue by yceny** [kosukeimai/MatchIt#64]
I am wondering for propensity score matching, what is the threshold to get the matched data? 

I understand I could use `machit` function with `method = 'nearest'` and `distance = 'glm'`, then use `match.data` to get matched data. 

Correct me if I am wrong. From my understanding, we need to specify a threshold for propensity score to get the matched data. Then what is the default threshold in the package? And is it possible we can choose the threshold on ourselves?

**Comment by ngreifer** [comment]
There are no thresholds involved, so I'm not sure what you mean. The matched data contains all the units that have been matched. Nearest neighbor matching involves find the nearest control unit to each treated unit and discarding the rest.

You might be thinking of a caliper, which is a limit on how far apart units can be to be able to be matched with each other. You can specify that with the `caliper` argument, but that is not a necessary part of matching. Please read [Austin (2011)](http://www.tandfonline.com/doi/abs/10.1080/00273171.2011.568786) and [Ho, Imai, King and Stuart (2007)](https://doi.org/10.1093/pan/mpl013) to understand how to conduct a matching analysis and what `MatchIt` does.

**Comment by yceny** [comment]
Thanks for your response. I read the two papers. They are very useful. Yes, caliper is what I mean here. One more clarification question. In `matchit` function, if we specify, say `caliper = 0.2`, does this mean 0.2 of the standard deviation of the logit of the propensity score?

**Comment by ngreifer** [comment]
Setting `caliper = .2` will by default use a caliper of .2 standard deviations of the distance measure. If the distance measure is the propensity score, then it will be .2 standard deviations of the propensity score. To make it the logit of the propensity score, use `link = "linear.logit"` in the call to `matchit()`. This will make the logit of the propensity score the distance used for matching and the variable to which the caliper is applied.
