### ISSUE TITLE
Set unique output labels (rownames in match$matrix)

### ISSUE THREAD

**Issue by nchemine** [kosukeimai/MatchIt#67]
And how can we set the rownames of the $match.matrix output to uniquely identify records in the data (e.g. using the "ID" or "name" field in the data) please? 

I am working on a 2mio records dataset and various subsets need to be matched, so indices are terribly error prone.

Thank you for your great work!

**Comment by ngreifer** [comment]
If you give your dataset row names (e.g., `rownames(data) <- paste0("unit", 1:nrow(data))`), the row names will be used in the `match.matrix` component of the output. These names are also used in the weights and subclass output so it will be straightforward to re-link them into your original dataset if you don't want to use `match.data()`.

Thank you for the kind words :)

**Comment by nchemine** [comment]
This works brilliantly as well! thank you!!
    Op vrijdag 30 april 2021 05:09:55 CEST schreef Noah Greifer ***@***.***>:  
 
 


If you give your dataset row names (e.g., rownames(data) <- paste0("unit", 1:nrow(data))), the row names will be used in the match.matrix component of the output. These names are also used in the weights and subclass output so it will be straightforward to re-link them into your original dataset if you don't want to use match.data().

Thank you for the kind words :)
