### ISSUE TITLE
Memory errors/segfault/unsorted double list corrupted errors

### ISSUE THREAD

**Issue by iacobus42** [kosukeimai/MatchIt#71]
I'm attempting to match a data with with roughly 1,000,000 observations. There are roughly 100,000 treated observations and 900,000 control observations. I unfortunately cannot share the data due to the data use agreement. I want to match using `"glm"` distance using a handful of covariates (I've tested 1 through 35 and get the same results). 

When I run 

```
matchit(treatment ~ age + charlson_index, data = mdata)
``` 

It estimates the PS model fine, tells me it is doing NN matching and then nearly immediately crashes with the error message `malloc(): unsorted double linked list corrupted`. Occasionally, it will return `error in nn_matchC invalid type NULL for dimnames`. In some instances It crashes telling me `Error in nn_matchC cannot get ALTVEC DATAPTR during GC` and (many) `recursive gc invocations` are printed out.

I have tried this code with this data on a server running CentOS Linux and two different machines, one running Ubuntu Linux and the other MacOS. I've tried this in R 3.5.2 and 4.04. I've also tried running inside a Docker container (rocker/verse). In all cases, the result is the same. I have uninstalled MatchIt and reinstalled from source instead of the binary files. That also did not fix the problem.

There is nothing wrong with the data that I can tell. If I subdivide mdata into 100 small n = 10,000 mutually exclusive and exhaustive bins, I can successfully run `matchit()` on each of the 100 bins. 

Additionally, I am interested in 5 different treatment comparisons (D1 vs D2, D1 vs no treatment, D2 vs no treatment, D1 vs D3, D2 vs D3). All of the data is from the same database but the data for matching for D2 vs no treatment and D2 vs D3 are the only sets that do not work. D1 vs D2, D1 vs no, and D1 vs D3 all work with `matchit()` exactly as expected.

**Comment by ngreifer** [comment]
Interesting. It will be hard to properly debug this without access to a dataset where this occurs. Have you tried using the updated development version on GitHub? I recently changed how the matching is done in Rcpp to improve speed and memory use.

**Comment by iacobus42** [comment]
@ngreifer I understand the issue about the data. I'm trying to make a repo that I can share that triggers it but haven't had success yet. 

I tried to install using `devtools::install_github("kosukeimai/MatchIt") but get the following:

```
> devtools::install_github("kosukeimai/MatchIt")
Downloading GitHub repo kosukeimai/MatchIt@HEAD
✓  checking for file ‘/private/var/folders/9w/rrpl__hs2v19x5bp7mbrx16x7l32td/T/RtmpkhXlIv/remotes1454c766d79d7/kosukeimai-MatchIt-e4d584c/DESCRIPTION’ ...
─  preparing ‘MatchIt’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
─  saving partial Rd database (25.9s)
─  cleaning src
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'quantifier does not follow a repeatable item'
   	at '*\.o$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^*\.o$'
   Execution halted
Error: Failed to install 'MatchIt' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * installing the package to process help pages
E> * saving partial Rd database
E> * cleaning src
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   PCRE pattern compilation error
E> 	'quantifier does not follow a repeatable item'
E> 	at '*\.o$'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   invalid regular expression '^*\.o$'
E> Execution halted
```

**Comment by iacobus42** [comment]
I was able to get commit a089c69 to install. The more recent commits all give the error listed in the post above. I'll let you know if this resolves the issue.

**Comment by iacobus42** [comment]
@ngreifer I was able to get it to crash using just the treatment variable and a covariate generated with `rnorm()` - although it wasn't consistently crashing but at least 20% of the attempts did. Since that only has sample size numbers and no PHI, I could share that with you if you want it for debugging purposes.

However, I've now successfully started roughly 20 calls to `matchit()` on datasets that were consistently crashing within seconds of starting before installing the GH version. The NN matching was taking a day or two (using the CRAN version) in the past, so I won't know if they finish successful for a while. That said, I was never having the issue mid-run, so I'm guessing some change between the CRAN version and a089c69 fixed whatever issue I was having.

**Comment by iacobus42** [comment]
I spoke too soon. It crashed. A shareable version of the data is posted as an RDS (~12mb) [here](https://drive.google.com/file/d/1ENL2s_y0DF4xQmDdjTCeG7sM-kuSGLZq/view?usp=sharing). There are two columns: 

* drug with values "trt" and "con" for treated and control
* x (result of `rnorm()`)

When I run the code in the block below, somewhat more than half of the time it crashes with a segfault and the message

```
address 0x30, cause 'memory not mapped'
malloc(): unsorted double linked list corrupted
```

```
library(tidyverse)
library(parallel)

# Load the data for matching
matching_data <- read_rds("~/example.rds")

# do the matching
# either runs fine (presumably) or crashes within a few seconds
matches <- MatchIt::matchit(drug ~ x,
                            data = matching_data,
                            caliper = 0.2, verbose = TRUE,
                            m.order = "random")
```

**Comment by ngreifer** [comment]
I am unable to replicate this using the dataset you provided. The matching takes a long time, of course, so I didn't let it run completely, but in all my experiments it never segfaults after several minutes of running. This may be a problem with your installation of `Rcpp` or a limitation of your setup. Looking around on the web, it could also be related to the use of the `parallel` package (which appears superfluous in your code since `MatchIt` cannot currently use parallelization methods). Do you get the same problem in a fresh R session without loading `parallel` or `tidyverse`?

**Comment by EarlGlynn** [comment]
Perhaps I'm seeing a related problem?

We're running 100s of numerical experiments using MatchIt 4.2.0 with R 4.1.0 with different variables in a formula selected from a few hundred possible variables.

We're seeing this error somewhat randomly:

```
Error in nn_matchC(treat, ord, ratio, max_rat, replace, discarded, distance, : invalid type (NULL) for 'dimnames' (must be a vector)
```

Re-running a matchit batch can fail at a different iteration each run.  For example, in running 1000 different combinations of two variables in the formula, failures occurred at the 187, 312, and 600th combinations.  This is not reproducible. 

Re-running the cases that fail work fine when run a second or third time (the random number seeds were preserved by run, so everything should be the same for a given combination).  Why does matchint occasionally fail with this `nn_match` error?

The `matchit` call is fairly simple:

```
  match11 <- matchit(as.formula(formulaString),
                         data = testDataComplete,
                         method = "nearest", 
                         distance = "glm")
```
where  (in the case the caused the traceback below):

* formulatString =  "matchitCase ~ MedicalData1 + MedicalData2"
* testDataComplete has 10,320 rows
* 
I did not find the traceback very informative:

```
. . . traceback was quite long
       replace = base::quote(FALSE), m.order = base::quote(NULL), 
       caliper = base::quote(NULL), s.weights = base::quote(NULL), 
       ratio = base::quote(1), is.full.mahalanobis = base::quote(FALSE), 
       formula = base::quote(matchitCase ~ MedicalData1 + 
           MedicalData2), estimand = base::quote("ATT"), verbose = base::quote(FALSE), 
       antiexact = base::quote(NULL))
2: do.call(fn2, list(treat = treat, covs = covs, data = data, distance = distance, 
       discarded = discarded, exact = exact, mahvars = mahvars, 
       replace = replace, m.order = m.order, caliper = caliper, 
       s.weights = s.weights, ratio = ratio, is.full.mahalanobis = is.full.mahalanobis, 
       formula = formula, estimand = estimand, verbose = verbose, 
       antiexact = antiexact, ...), quote = TRUE)
1: matchit(as.formula(formulaString), data = testDataComplete, method = "nearest", 
       distance = "glm")
```

Could this be some sort of memory issue?  Can you suggest any troubleshooting steps?  What does the error message mean?

**Comment by ngreifer** [comment]
So sorry this is happening. Unfortunately, I am unable to reproduce this problem running `matchit()` 12000 times in a loop on macOS. I have a feeling I know where that error is occurring because there is only one place where dim names are referenced. I've made a change that will hopefully help, but since I can't recreate the error, I don't know if it will help and there isn't much I can do. This is clearly a problem with memory allocation in`Rcpp`, something I don't at all understand. I will follow up with a demon of `MatchIt` with my attempt at solving this issue shortly.

**Comment by SulevR** [comment]
It is just to let you know that after I started using MatchIt package (particularly matchit() function) in my package (not public yet), it tends to crash with or without some weird messages. The last time RStudio simply crashed, the previous time I got message like

`invalid type (NULL) for 'dimnames'
`

However, just after restarting everything then worked well, so it can't be a data issue. At the same time, I do not run matchit() extensively - perhaps only a few dozen or a hundred times... So, all in all, it is quite annoying problem.

**Comment by ngreifer** [comment]
I am so sorry this is happening. I am unable to replicate this issue (I can run `MatchIt` thousands of times with no problems) so it is hard for me to diagnose it, but I have made a number of edits in the upcoming version of `MatchIt` that should be on CRAN soon. Have you tried installing the development version using `devtools::install_github("ngreifer/MatchIt")`? Have you tried making sure `Rcpp` is up to date?

**Comment by SulevR** [comment]
I did
`devtools::install_github("ngreifer/MatchIt")`
which asked me whether I update Rcpp (I updated `Rcpp 1.0.6->1.0.7`)

Since then, I haven't had any crashes so far. Previously, it crashed in every hour. So, I keep fingers crossed!
