### ISSUE TITLE
Build-In Sensitivity Test

### ISSUE THREAD

**Issue by sammo3182** [kosukeimai/MatchIt#73]
It's difficult to conduct a sensitivity test (Rosenbaum 2007) for `MatchiIt` objects. Within the existing "sensitivity*" packages, only a github version (`SensitivityR5`) can conduct the test but apparently only with objects with `method = "nearest"`. It would be great if the original "MatchIt" function has a similar `pens` function as in `rbounds` for `Matching" projects.

**Comment by ngreifer** [comment]
That's a good idea. I agree that sensitivity analyses should be easier to implement for `matchit` objects and more generally. However, the type of sensitivity analysis done by `rbounds` is very specific and generally does not correspond to the methods of estimation most commonly used with matching (t-tests and regression adjustment). For now, I recommend you look into VanderWeele and Dings' e-value as implemented in the `EValue` package, which provides a sensitivity analysis for the most common effect measures resulting from a matching analysis and can be used with output from any package.

**Comment by sammo3182** [comment]
Thank you so much for the suggestion of Noah @ngreifer! `EValue` works! Just a quick reminder for the users who intend to conduct such tests, `EValue` package seems to have a conflict with `caret` package. Don't load both together, otherwise, you might get an error when running the `evalues.*` functions.
