### ISSUE TITLE
Exact matching produces more then one case per subclass

### ISSUE THREAD

**Issue by AlinaVod** [kosukeimai/MatchIt#78]
I am using 'MatchIt' package to match cases to controls. I would like to match by age and four other binary variables.

`match_exact <- matchit(case_control~ age+var1+var2+var3+var4, cutpoints = list(age = 10),
                data = df, method="exact")
match_exact_data <- match.data(match_exact)`

Then I extract the matched data and I would like to know the id's of cases to which control they were matched.
In the subclass strata I see more then one case. I would assume there would be one case and one or more controls. Does that makes sense?

**Comment by ngreifer** [comment]
I responded to your [question](https://stackoverflow.com/questions/68372793/clarification-about-subclass-in-matchit-package-in-r) SO. Please read the linked post and let me know if you still have questions. Also see the [documentation](https://kosukeimai.github.io/MatchIt/reference/method_exact.html) for exact matching and the [vignette](https://kosukeimai.github.io/MatchIt/articles/matching-methods.html) explaining matching methods. 

No pairing is done with exact matching, so it doesn't make sense to talk about which control is matched to each treated unit. Also, the `cutpoints` argument is ignored with `method = "exact"`. It sounds like you might want `method = "cem"` with `k2k = TRUE`, but I argue in the linked post that there is essentially no good reason to do this and you are only throwing away good data.
