### ISSUE TITLE
handling of missing data

### ISSUE THREAD

**Issue by kosukeimai** [kosukeimai/MatchIt#8]
Currently, one cannot have missing values even in variables that are not used for matching.  This should be fixed so that the function only checks the existence of missing values for the variables that are used.

**Comment by alexWhitworth** [comment]
@kosukeimai Could we also cleanup the R files associated with this issue? There are currently 8 `*.R` files associated with different methods, each of which is a relatively small file. The code would be much more maintainable if these separate files were merged to a single `matchit2_methods.R` file... at any rate, that's my $0.02 :)

**Comment by changchris** [comment]
agree - just ran into this issue.

**Comment by mylanhong** [comment]
@kosukeimai Agree with you.

**Comment by s14230** [comment]
Hi, Is this fixed yet? It's an important limitation

**Comment by dspagnolo09** [comment]
Also running into this issue.

**Comment by ngreifer** [comment]
Fixed.
