### ISSUE TITLE
MatchIt get stuck

### ISSUE THREAD

**Issue by giuliogcantone** [kosukeimai/MatchIt#81]
(EDIT: I SOLVED IT.

It seems Rcpp would never install itself correctly UNTIL you upgrade RTools. It will show it working but it will not.
Once I upgraded RTools and re-installed from scratch Rcpp, it upgraded to a version working with MatchIt)

Hello.

Even when I try to run the simplest code on tiny dataset (nrow = 300), matchit runs indefinitely. When I press the red stop, nothing happens and to make it stop I need to shut down R Studio.

`matchit(K ~ P, data = DB,
        replace = F) -> matchedDB`

May be that DB is a tibble? The only suspicious part is that MatchIt doesn't call by itself Rcpp. Instead, I need to activate it manually. This is the error:

```
Error in nn_matchC(treat, ord, ratio, max_rat, replace, discarded, distance,  : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```

**Comment by ngreifer** [comment]
Glad this was solved.
