### ISSUE TITLE
Weights for full matching seem wrong

### ISSUE THREAD

**Issue by jiweihe1223** [kosukeimai/MatchIt#83]
I used the example dataset and applied full matching. 
Below is the output for 5 matched clusters. 
The weights look strange. They don't fit any formula I can think of. The document did not explain this case.

```
        treat     weights subclass
NSW1        1  1.00000000        1
PSID69      0  2.31891892        1
NSW21       1  1.00000000        2
NSW24       1  1.00000000        2
NSW27       1  1.00000000        2
NSW30       1  1.00000000        2
NSW63       1  1.00000000        2
NSW72       1  1.00000000        2
NSW75       1  1.00000000        2
NSW80       1  1.00000000        2
NSW93       1  1.00000000        2
NSW103      1  1.00000000        2
NSW106      1  1.00000000        2
NSW159      1  1.00000000        2
PSID196     0 27.82702703        2
NSW22       1  1.00000000        3
PSID127     0  2.31891892        3
NSW23       1  1.00000000        4
PSID182     0  0.38648649        4
PSID207     0  0.38648649        4
PSID353     0  0.38648649        4
PSID357     0  0.38648649        4
PSID405     0  0.38648649        4
PSID425     0  0.38648649        4
NSW26       1  1.00000000        5
NSW55       1  1.00000000        5
PSID335     0  4.63783784        5
```

**Comment by ngreifer** [comment]
I'm not sure if you're the same person who [asked](https://stats.stackexchange.com/questions/536197/how-are-weights-computed-in-r-matchit-function-for-full-matching/536202#536202) about this on CrossValidated, but the weights are computed using the procedure described in the documentation for `?matchit`. The steps are as follows: 1) estimate a "subclass propensity score" as the proportion of treated units in each subclass, and assign that to each member of the subclass, 2) use the formula for calculating propensity score weights for the desired estimand (in this case the ATT) on the subclass propensity scores, 3) divide the weights in each treatment group by the average of the weights in that treatment group. Below I demonstrate that the weights computed by `matchit()` are equal to weights computed manually from the subclasses.

``` r
library(MatchIt)
data("lalonde")

#Full matching ATT
m <- matchit(treat ~ age + educ + race + married + nodegree + re74 + re75, 
             data = lalonde, method = "full")

#Computing weights manually from subclasses
##Initialize subclass PS
p <- rep(0, 614) 
##Compute subclass PS as proportion of treated in each subclass
for (i in unique(m$subclass)) {
  p[m$subclass == i] <- mean(m$treat[m$subclass==i] == 1)
}
#Apply ATT formula to subclass PS to compute weights
w <- ifelse(m$treat == 1, 1, p/(1-p))
#Divide control group weights by their mean
w[m$treat == 0] <- w[m$treat==0]/mean(w[m$treat==0])

#Are matchit() weights equal to manual weights?
all.equal(m$weights, w)
#> [1] TRUE

#Yes!
```

<sup>Created on 2021-07-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

You can see that these weights are exactly the weights displayed in your post. They are nothing more than scaled inverse probability weights computed using standard formulas.

**Comment by jiweihe1223** [comment]
thanks a lot. yes this is the same person. 
I missed the part about "divide the weights in each treatment group by the average of the weights in that treatment group."
Intuitively I am still thinking why the weights are calculated this way and whether this is consistent with stratified analysis by matching cluster. May have more question later.

**Comment by ngreifer** [comment]
It is consistent. Using the weights or stratified analysis will give you the same result, which is why the weights are calculated as they are. If you compute the stratum-specific mean differences and then average them, giving each one a weight equal to the proportion of the treated units that are in that stratum (for the ATT), you get the same result as computing a weighted mean using the computed weights. See below:

```
> weighted.mean(lalonde$re78[lalonde$treat==1], m$weights[lalonde$treat==1]) - 
+   weighted.mean(lalonde$re78[lalonde$treat==0], m$weights[lalonde$treat==0])
[1] 1737.947
> 
> sum(sapply(unique(m$subclass), function(i) {
+   mean(m$subclass[lalonde$treat==1]==i) * (
+     mean(lalonde$re78[lalonde$treat==1 & m$subclass==i]) - 
+       mean(lalonde$re78[lalonde$treat==0 & m$subclass==i]))}))
[1] 1737.947
```
If you instead weight each subclass-specific effect by the proportion of all units in the sample in each subclass, you get an equivalent estimate to the ATE estimate.

**Comment by jiweihe1223** [comment]
I see. thanks a lot for the explanation.

**Comment by ngreifer** [comment]
No problem, glad it was helpful.
