### ISSUE TITLE
implementing Rubin and Thomas (2000) from JASA

### ISSUE THREAD

**Issue by yceny** [kosukeimai/MatchIt#84]
I am reading [Ho et al. (2017)](https://www.cambridge.org/core/journals/political-analysis/article/matching-as-nonparametric-preprocessing-for-reducing-model-dependence-in-parametric-causal-inference/4D7E6D07C9727F5A604E5C9FCCA2DD21), which I believe is how `MatchIt` is built upon. 

The paper referenced Rubin and Thomas (2000) from JASA. Wondering how I could implement the ideas in this paper in `MatchIt`? i.e, match on the propensity score first, then adjust based on some special covariates using Mahalanobis distance.

**Comment by ngreifer** [comment]
This is explained in the Details section at `?method_nearest`, which you can also view [here](https://kosukeimai.github.io/MatchIt/reference/method_nearest.html).
