### ISSUE TITLE
Missing output for matchit.subclass

### ISSUE THREAD

**Issue by aldencabajar** [kosukeimai/MatchIt#92]
I've noticed that using method `subclass` does not also output the other values as returned by  function `matchit2subclass `.
the `method = 'subclass'` argument outputs this list:
https://github.com/kosukeimai/MatchIt/blob/a2d14fe388b75098139bbff18172ab1e1231b0b0/R/matchit2_methods.R#L1057-L1059

But looking at the return list for the main function `matchit`, `q,cut` and `qn` are nowhere to be found:

https://github.com/kosukeimai/MatchIt/blob/a2d14fe388b75098139bbff18172ab1e1231b0b0/R/matchit.R#L264-L283

Let me know if I'm understanding it correctly. Thanks!

**Comment by ngreifer** [comment]
Ah yes, that is an error. Thank you for pointing it out.
